#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("FormsDemo.Droid.Resource", IsApplication=true)]

namespace FormsDemo.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int applause_edit_screeshot_fadein = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int applause_edit_screeshot_fadeout = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int applause_forgot_passcode_hide_to_left = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int applause_forgot_passcode_hide_to_right = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int applause_forgot_passcode_show_from_left = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int applause_forgot_passcode_show_from_right = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int applause_login_fadein = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int applause_login_fadeout = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int applause_slide_in = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int applause_slide_out = 2130968585;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Boolean
		{
			
			// aapt resource value: 0x7f060000
			public const int applause_default_circle_indicator_centered = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int applause_default_circle_indicator_snap = 2131099649;
			
			static Boolean()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Boolean()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f070000
			public const int applause_beta_forgot_passcode = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int applause_beta_title = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int applause_black = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int applause_blue = 2131165187;
			
			// aapt resource value: 0x7f070004
			public const int applause_brightRed = 2131165188;
			
			// aapt resource value: 0x7f070005
			public const int applause_button_bg = 2131165189;
			
			// aapt resource value: 0x7f070006
			public const int applause_button_bg_disabled = 2131165190;
			
			// aapt resource value: 0x7f070007
			public const int applause_button_bg_pressed = 2131165191;
			
			// aapt resource value: 0x7f070008
			public const int applause_button_dark_bg = 2131165192;
			
			// aapt resource value: 0x7f070009
			public const int applause_button_dark_bg_disabled = 2131165193;
			
			// aapt resource value: 0x7f07000a
			public const int applause_button_dark_bg_pressed = 2131165194;
			
			// aapt resource value: 0x7f07000b
			public const int applause_button_dark_text = 2131165195;
			
			// aapt resource value: 0x7f07000c
			public const int applause_button_feedback_bg = 2131165196;
			
			// aapt resource value: 0x7f07000d
			public const int applause_button_feedback_bg_disabled = 2131165197;
			
			// aapt resource value: 0x7f07000e
			public const int applause_button_feedback_bg_pressed = 2131165198;
			
			// aapt resource value: 0x7f07000f
			public const int applause_button_feedback_text = 2131165199;
			
			// aapt resource value: 0x7f070010
			public const int applause_button_problem_bg = 2131165200;
			
			// aapt resource value: 0x7f070011
			public const int applause_button_problem_bg_disabled = 2131165201;
			
			// aapt resource value: 0x7f070012
			public const int applause_button_problem_bg_pressed = 2131165202;
			
			// aapt resource value: 0x7f070013
			public const int applause_button_problem_text = 2131165203;
			
			// aapt resource value: 0x7f070014
			public const int applause_button_text = 2131165204;
			
			// aapt resource value: 0x7f070015
			public const int applause_button_text_shadow = 2131165205;
			
			// aapt resource value: 0x7f070016
			public const int applause_darkBlack = 2131165206;
			
			// aapt resource value: 0x7f070017
			public const int applause_darkBlue = 2131165207;
			
			// aapt resource value: 0x7f070018
			public const int applause_darkGreen = 2131165208;
			
			// aapt resource value: 0x7f070019
			public const int applause_darkGrey = 2131165209;
			
			// aapt resource value: 0x7f07001a
			public const int applause_darkLime = 2131165210;
			
			// aapt resource value: 0x7f07001b
			public const int applause_darkOrange = 2131165211;
			
			// aapt resource value: 0x7f07001c
			public const int applause_darkRed = 2131165212;
			
			// aapt resource value: 0x7f07001d
			public const int applause_darkSteel = 2131165213;
			
			// aapt resource value: 0x7f07001e
			public const int applause_darkWhite = 2131165214;
			
			// aapt resource value: 0x7f07001f
			public const int applause_darkYellow = 2131165215;
			
			// aapt resource value: 0x7f070020
			public const int applause_default_circle_indicator_fill_color = 2131165216;
			
			// aapt resource value: 0x7f070021
			public const int applause_default_circle_indicator_page_color = 2131165217;
			
			// aapt resource value: 0x7f070022
			public const int applause_default_circle_indicator_stroke_color = 2131165218;
			
			// aapt resource value: 0x7f070023
			public const int applause_dialog_bg = 2131165219;
			
			// aapt resource value: 0x7f070024
			public const int applause_dialog_button_bg = 2131165220;
			
			// aapt resource value: 0x7f070025
			public const int applause_dialog_button_bg_pressed = 2131165221;
			
			// aapt resource value: 0x7f070026
			public const int applause_dialog_button_text = 2131165222;
			
			// aapt resource value: 0x7f070027
			public const int applause_dialog_button_text_primary = 2131165223;
			
			// aapt resource value: 0x7f070028
			public const int applause_dialog_divider = 2131165224;
			
			// aapt resource value: 0x7f070029
			public const int applause_dialog_panel_bg = 2131165225;
			
			// aapt resource value: 0x7f07002a
			public const int applause_dialog_panel_header = 2131165226;
			
			// aapt resource value: 0x7f07002b
			public const int applause_dialog_panel_text = 2131165227;
			
			// aapt resource value: 0x7f07002c
			public const int applause_dialog_shadow = 2131165228;
			
			// aapt resource value: 0x7f07002d
			public const int applause_dialog_text = 2131165229;
			
			// aapt resource value: 0x7f07002e
			public const int applause_dialog_title = 2131165230;
			
			// aapt resource value: 0x7f07002f
			public const int applause_editor_bg = 2131165231;
			
			// aapt resource value: 0x7f070030
			public const int applause_editor_footer_bg = 2131165232;
			
			// aapt resource value: 0x7f070031
			public const int applause_editor_header_bg = 2131165233;
			
			// aapt resource value: 0x7f070032
			public const int applause_editor_header_text = 2131165234;
			
			// aapt resource value: 0x7f070033
			public const int applause_error_bg = 2131165235;
			
			// aapt resource value: 0x7f070034
			public const int applause_error_text = 2131165236;
			
			// aapt resource value: 0x7f070035
			public const int applause_feedback_dialog_bug_circle_color = 2131165237;
			
			// aapt resource value: 0x7f070036
			public const int applause_feedback_dialog_bug_circle_color_pressed = 2131165238;
			
			// aapt resource value: 0x7f070037
			public const int applause_feedback_header_bg = 2131165239;
			
			// aapt resource value: 0x7f070038
			public const int applause_feedback_header_text = 2131165240;
			
			// aapt resource value: 0x7f070039
			public const int applause_footer_text = 2131165241;
			
			// aapt resource value: 0x7f07003a
			public const int applause_green = 2131165242;
			
			// aapt resource value: 0x7f07003b
			public const int applause_grey = 2131165243;
			
			// aapt resource value: 0x7f07003c
			public const int applause_header_bg = 2131165244;
			
			// aapt resource value: 0x7f07003d
			public const int applause_header_button_bg = 2131165245;
			
			// aapt resource value: 0x7f07003e
			public const int applause_header_button_bg_pressed = 2131165246;
			
			// aapt resource value: 0x7f07003f
			public const int applause_header_text = 2131165247;
			
			// aapt resource value: 0x7f070040
			public const int applause_input_bg = 2131165248;
			
			// aapt resource value: 0x7f070041
			public const int applause_input_border = 2131165249;
			
			// aapt resource value: 0x7f070042
			public const int applause_input_border_active = 2131165250;
			
			// aapt resource value: 0x7f070043
			public const int applause_input_hint = 2131165251;
			
			// aapt resource value: 0x7f070044
			public const int applause_input_text = 2131165252;
			
			// aapt resource value: 0x7f070045
			public const int applause_lightBlack = 2131165253;
			
			// aapt resource value: 0x7f070046
			public const int applause_lightBlue = 2131165254;
			
			// aapt resource value: 0x7f070047
			public const int applause_lightGreen = 2131165255;
			
			// aapt resource value: 0x7f070048
			public const int applause_lightGrey = 2131165256;
			
			// aapt resource value: 0x7f070049
			public const int applause_lightRed = 2131165257;
			
			// aapt resource value: 0x7f07004a
			public const int applause_lightSteel = 2131165258;
			
			// aapt resource value: 0x7f07004b
			public const int applause_lightYellow = 2131165259;
			
			// aapt resource value: 0x7f07004c
			public const int applause_lime = 2131165260;
			
			// aapt resource value: 0x7f07004d
			public const int applause_material_grey = 2131165261;
			
			// aapt resource value: 0x7f07004e
			public const int applause_material_light_grey = 2131165262;
			
			// aapt resource value: 0x7f07004f
			public const int applause_material_line_grey = 2131165263;
			
			// aapt resource value: 0x7f070050
			public const int applause_mediumGrey = 2131165264;
			
			// aapt resource value: 0x7f070051
			public const int applause_orange = 2131165265;
			
			// aapt resource value: 0x7f070052
			public const int applause_paleBlack = 2131165266;
			
			// aapt resource value: 0x7f070053
			public const int applause_paleBlue = 2131165267;
			
			// aapt resource value: 0x7f070054
			public const int applause_paleGrey = 2131165268;
			
			// aapt resource value: 0x7f070055
			public const int applause_paleSteel = 2131165269;
			
			// aapt resource value: 0x7f070056
			public const int applause_problem_header_bg = 2131165270;
			
			// aapt resource value: 0x7f070057
			public const int applause_problem_header_text = 2131165271;
			
			// aapt resource value: 0x7f070058
			public const int applause_red = 2131165272;
			
			// aapt resource value: 0x7f070059
			public const int applause_report_attachment = 2131165273;
			
			// aapt resource value: 0x7f07005a
			public const int applause_report_bg_bottom = 2131165274;
			
			// aapt resource value: 0x7f07005b
			public const int applause_report_bg_top = 2131165275;
			
			// aapt resource value: 0x7f07005c
			public const int applause_report_dialog_bug_circle_color = 2131165276;
			
			// aapt resource value: 0x7f07005d
			public const int applause_report_dialog_bug_circle_color_pressed = 2131165277;
			
			// aapt resource value: 0x7f07005e
			public const int applause_report_second_text = 2131165278;
			
			// aapt resource value: 0x7f07005f
			public const int applause_report_text = 2131165279;
			
			// aapt resource value: 0x7f07007c
			public const int applause_severity_color_selector = 2131165308;
			
			// aapt resource value: 0x7f070060
			public const int applause_severity_inner_circle = 2131165280;
			
			// aapt resource value: 0x7f070061
			public const int applause_severity_line_color = 2131165281;
			
			// aapt resource value: 0x7f070062
			public const int applause_severity_normal_color = 2131165282;
			
			// aapt resource value: 0x7f070063
			public const int applause_severity_selected_color = 2131165283;
			
			// aapt resource value: 0x7f070064
			public const int applause_steel = 2131165284;
			
			// aapt resource value: 0x7f070065
			public const int applause_subheader_bg = 2131165285;
			
			// aapt resource value: 0x7f070066
			public const int applause_subheader_text = 2131165286;
			
			// aapt resource value: 0x7f070067
			public const int applause_transparent = 2131165287;
			
			// aapt resource value: 0x7f070068
			public const int applause_transparent_darkGrey = 2131165288;
			
			// aapt resource value: 0x7f070069
			public const int applause_transparent_grey = 2131165289;
			
			// aapt resource value: 0x7f07006a
			public const int applause_tutorial_bottom_bar_background = 2131165290;
			
			// aapt resource value: 0x7f07006b
			public const int applause_tutorial_buttons_text = 2131165291;
			
			// aapt resource value: 0x7f07006c
			public const int applause_tutorial_darkGray = 2131165292;
			
			// aapt resource value: 0x7f07006d
			public const int applause_tutorial_gray = 2131165293;
			
			// aapt resource value: 0x7f07006e
			public const int applause_tutorial_next_steps_background = 2131165294;
			
			// aapt resource value: 0x7f07006f
			public const int applause_tutorial_step2_main_font_color = 2131165295;
			
			// aapt resource value: 0x7f070070
			public const int applause_tutorial_step2_secondary_font_color = 2131165296;
			
			// aapt resource value: 0x7f070071
			public const int applause_tutorial_step3_font_color = 2131165297;
			
			// aapt resource value: 0x7f070072
			public const int applause_type_chooser_dialog_text_color = 2131165298;
			
			// aapt resource value: 0x7f070073
			public const int applause_user_list_bg = 2131165299;
			
			// aapt resource value: 0x7f070074
			public const int applause_user_list_bg_pressed = 2131165300;
			
			// aapt resource value: 0x7f070075
			public const int applause_user_list_divider = 2131165301;
			
			// aapt resource value: 0x7f070076
			public const int applause_user_list_text = 2131165302;
			
			// aapt resource value: 0x7f070077
			public const int applause_user_list_text_pressed = 2131165303;
			
			// aapt resource value: 0x7f070078
			public const int applause_violet = 2131165304;
			
			// aapt resource value: 0x7f070079
			public const int applause_welcome_content_text = 2131165305;
			
			// aapt resource value: 0x7f07007a
			public const int applause_white = 2131165306;
			
			// aapt resource value: 0x7f07007b
			public const int applause_yellow = 2131165307;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f080000
			public const int applause_default_circle_indicator_radius = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int applause_default_circle_indicator_stroke_width = 2131230721;
			
			// aapt resource value: 0x7f080002
			public const int applause_dialog_horizontal_margin = 2131230722;
			
			// aapt resource value: 0x7f080003
			public const int applause_dialog_vertical_margin = 2131230723;
			
			// aapt resource value: 0x7f080004
			public const int applause_report_dialog_buttons_distance = 2131230724;
			
			// aapt resource value: 0x7f080005
			public const int applause_screenshot_height = 2131230725;
			
			// aapt resource value: 0x7f080006
			public const int applause_screenshot_thumbnail_edit_button_height = 2131230726;
			
			// aapt resource value: 0x7f080007
			public const int applause_screenshot_width = 2131230727;
			
			// aapt resource value: 0x7f080008
			public const int applause_severity_dot_radius = 2131230728;
			
			// aapt resource value: 0x7f080009
			public const int applause_severity_label_top_padding = 2131230729;
			
			// aapt resource value: 0x7f08000a
			public const int applause_severity_line_height = 2131230730;
			
			// aapt resource value: 0x7f08000b
			public const int applause_severity_line_top_margin = 2131230731;
			
			// aapt resource value: 0x7f08000c
			public const int applause_severity_slider_height = 2131230732;
			
			// aapt resource value: 0x7f08000d
			public const int applause_tutorial_bottom_bar_height = 2131230733;
			
			// aapt resource value: 0x7f08000e
			public const int applause_tutorial_label_padding = 2131230734;
			
			// aapt resource value: 0x7f08000f
			public const int applause_tutorial_label_text_size = 2131230735;
			
			// aapt resource value: 0x7f080010
			public const int applause_tutorial_side_bar_size = 2131230736;
			
			// aapt resource value: 0x7f080011
			public const int applause_tutorial_step2_image_margin_top = 2131230737;
			
			// aapt resource value: 0x7f080012
			public const int applause_tutorial_step2_image_width = 2131230738;
			
			// aapt resource value: 0x7f080013
			public const int applause_tutorial_step2_label2_margin_top = 2131230739;
			
			// aapt resource value: 0x7f080014
			public const int applause_tutorial_step2_labels_padding = 2131230740;
			
			// aapt resource value: 0x7f080015
			public const int applause_tutorial_top_bar_size = 2131230741;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int applause_avatar = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int applause_avatar_mask = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int applause_background = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int applause_beta_dialog_header_background = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int applause_btn_check_off_focused_holo_dark = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int applause_btn_check_off_holo_dark = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int applause_btn_check_off_pressed_holo_dark = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int applause_btn_check_on_focused_holo_dark = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int applause_btn_check_on_holo_dark = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int applause_btn_check_on_pressed_holo_dark = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int applause_button = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int applause_button_dark = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int applause_button_feedback = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int applause_button_problem = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int applause_checkbox = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int applause_circle_button = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int applause_circle_button_feedback = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int applause_circle_button_problem = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int applause_color_cursor = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int applause_dialog_background = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int applause_dialog_button = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int applause_dialog_footer_background = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int applause_dialog_header_background = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int applause_editor_button = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int applause_header_button = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int applause_ic_warn = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int applause_input = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int applause_loader = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int applause_problem_bottom_shadow = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int applause_problem_top_shadow = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int applause_rating = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int applause_report_bug_circle = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int applause_report_feedback_circle = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int applause_screenshot_thumbnail_overlay = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int applause_severity_slider_normal_dot = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int applause_severity_slider_selected_dot = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int applause_star = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int applause_star_active = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int applause_star_normal = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int applause_star_pressed = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int applause_textbox = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int applause_tutorial_button_background = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int applause_tutorial_left_bar = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int applause_tutorial_right_bar = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int applause_tutorial_screenshot_small = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int applause_tutorial_shadow_overlay = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int applause_tutorial_step_2 = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int applause_tutorial_tooltip_bug_message = 2130837551;
			
			// aapt resource value: 0x7f020030
			public const int applause_tutorial_tooltip_feedback_rating = 2130837552;
			
			// aapt resource value: 0x7f020031
			public const int applause_tutorial_tooltip_feedback_review = 2130837553;
			
			// aapt resource value: 0x7f020032
			public const int applause_tutorial_tooltip_horizontal_list = 2130837554;
			
			// aapt resource value: 0x7f020033
			public const int applause_tutorial_top_bar = 2130837555;
			
			// aapt resource value: 0x7f020034
			public const int applause_tutorial_top_left_corner = 2130837556;
			
			// aapt resource value: 0x7f020035
			public const int applause_tutorial_top_right_corner = 2130837557;
			
			// aapt resource value: 0x7f020036
			public const int applause_user_list_background = 2130837558;
			
			// aapt resource value: 0x7f020037
			public const int applause_user_list_textcolor = 2130837559;
			
			// aapt resource value: 0x7f020038
			public const int applause_video_cancel_action = 2130837560;
			
			// aapt resource value: 0x7f020039
			public const int applause_video_play = 2130837561;
			
			// aapt resource value: 0x7f02003a
			public const int applause_video_play_button = 2130837562;
			
			// aapt resource value: 0x7f02003b
			public const int applause_video_save_action = 2130837563;
			
			// aapt resource value: 0x7f02003c
			public const int icon = 2130837564;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f0c0035
			public const int applause_container = 2131492917;
			
			// aapt resource value: 0x7f0c0016
			public const int applause_feedback_include_screenshot_check_box = 2131492886;
			
			// aapt resource value: 0x7f0c0014
			public const int applause_feedback_rating_bar = 2131492884;
			
			// aapt resource value: 0x7f0c0015
			public const int applause_feedback_rating_bar_tooltip_hook = 2131492885;
			
			// aapt resource value: 0x7f0c003e
			public const int applause_gallery_next = 2131492926;
			
			// aapt resource value: 0x7f0c0004
			public const int applause_generic_dialog_body = 2131492868;
			
			// aapt resource value: 0x7f0c0005
			public const int applause_generic_dialog_negative_btn = 2131492869;
			
			// aapt resource value: 0x7f0c0006
			public const int applause_generic_dialog_positive_btn = 2131492870;
			
			// aapt resource value: 0x7f0c0003
			public const int applause_generic_dialog_title = 2131492867;
			
			// aapt resource value: 0x7f0c001a
			public const int applause_header_quick_subheader = 2131492890;
			
			// aapt resource value: 0x7f0c0021
			public const int applause_login_anonymous_layout = 2131492897;
			
			// aapt resource value: 0x7f0c0002
			public const int applause_login_app_version = 2131492866;
			
			// aapt resource value: 0x7f0c0019
			public const int applause_login_btn_anon_login = 2131492889;
			
			// aapt resource value: 0x7f0c0020
			public const int applause_login_btn_login = 2131492896;
			
			// aapt resource value: 0x7f0c0000
			public const int applause_login_dialog_password_auth_view = 2131492864;
			
			// aapt resource value: 0x7f0c001e
			public const int applause_login_email_edit = 2131492894;
			
			// aapt resource value: 0x7f0c001d
			public const int applause_login_error_close = 2131492893;
			
			// aapt resource value: 0x7f0c001b
			public const int applause_login_error_container = 2131492891;
			
			// aapt resource value: 0x7f0c001c
			public const int applause_login_error_text = 2131492892;
			
			// aapt resource value: 0x7f0c0001
			public const int applause_login_loading_page = 2131492865;
			
			// aapt resource value: 0x7f0c001f
			public const int applause_login_password_edit = 2131492895;
			
			// aapt resource value: 0x7f0c0023
			public const int applause_login_progress_container = 2131492899;
			
			// aapt resource value: 0x7f0c0024
			public const int applause_login_progress_user = 2131492900;
			
			// aapt resource value: 0x7f0c0022
			public const int applause_login_users_list = 2131492898;
			
			// aapt resource value: 0x7f0c000c
			public const int applause_overlay = 2131492876;
			
			// aapt resource value: 0x7f0c000e
			public const int applause_overlay_delete_screenshot = 2131492878;
			
			// aapt resource value: 0x7f0c0013
			public const int applause_overlay_eraser = 2131492883;
			
			// aapt resource value: 0x7f0c000f
			public const int applause_overlay_go_report = 2131492879;
			
			// aapt resource value: 0x7f0c000d
			public const int applause_overlay_header = 2131492877;
			
			// aapt resource value: 0x7f0c0011
			public const int applause_overlay_pencil = 2131492881;
			
			// aapt resource value: 0x7f0c0012
			public const int applause_overlay_spray = 2131492882;
			
			// aapt resource value: 0x7f0c0010
			public const int applause_overlay_toolbar = 2131492880;
			
			// aapt resource value: 0x7f0c0025
			public const int applause_problem_horizontal_list = 2131492901;
			
			// aapt resource value: 0x7f0c0026
			public const int applause_problem_horizontal_list_sample = 2131492902;
			
			// aapt resource value: 0x7f0c002a
			public const int applause_problem_horizontal_list_tooltip_hook = 2131492906;
			
			// aapt resource value: 0x7f0c0017
			public const int applause_problem_scroll_view = 2131492887;
			
			// aapt resource value: 0x7f0c0030
			public const int applause_report_add_button = 2131492912;
			
			// aapt resource value: 0x7f0c0009
			public const int applause_report_add_from_camera = 2131492873;
			
			// aapt resource value: 0x7f0c0008
			public const int applause_report_add_from_gallery = 2131492872;
			
			// aapt resource value: 0x7f0c0007
			public const int applause_report_add_screenshot = 2131492871;
			
			// aapt resource value: 0x7f0c0028
			public const int applause_report_bug_edit_tooltip_hook = 2131492904;
			
			// aapt resource value: 0x7f0c0032
			public const int applause_report_bug_test_cycle_name = 2131492914;
			
			// aapt resource value: 0x7f0c0031
			public const int applause_report_bug_title = 2131492913;
			
			// aapt resource value: 0x7f0c0034
			public const int applause_report_bug_wifi_only = 2131492916;
			
			// aapt resource value: 0x7f0c0033
			public const int applause_report_bug_wifi_only_label = 2131492915;
			
			// aapt resource value: 0x7f0c0037
			public const int applause_report_dialog_bug = 2131492919;
			
			// aapt resource value: 0x7f0c0038
			public const int applause_report_dialog_feedback = 2131492920;
			
			// aapt resource value: 0x7f0c0029
			public const int applause_report_feedback_edit_tooltip_hook = 2131492905;
			
			// aapt resource value: 0x7f0c002e
			public const int applause_report_message_action_performed = 2131492910;
			
			// aapt resource value: 0x7f0c002f
			public const int applause_report_message_action_performed_bar = 2131492911;
			
			// aapt resource value: 0x7f0c002c
			public const int applause_report_message_actual_result = 2131492908;
			
			// aapt resource value: 0x7f0c002d
			public const int applause_report_message_actual_result_bar = 2131492909;
			
			// aapt resource value: 0x7f0c0027
			public const int applause_report_message_edit = 2131492903;
			
			// aapt resource value: 0x7f0c002b
			public const int applause_report_message_edit_bar = 2131492907;
			
			// aapt resource value: 0x7f0c000b
			public const int applause_report_take_video = 2131492875;
			
			// aapt resource value: 0x7f0c000a
			public const int applause_report_take_video_notice = 2131492874;
			
			// aapt resource value: 0x7f0c0039
			public const int applause_screenshot_container = 2131492921;
			
			// aapt resource value: 0x7f0c003d
			public const int applause_screenshot_label = 2131492925;
			
			// aapt resource value: 0x7f0c003f
			public const int applause_screenshot_loader = 2131492927;
			
			// aapt resource value: 0x7f0c003b
			public const int applause_screenshot_overlay = 2131492923;
			
			// aapt resource value: 0x7f0c003a
			public const int applause_screenshot_small = 2131492922;
			
			// aapt resource value: 0x7f0c0018
			public const int applause_send_report = 2131492888;
			
			// aapt resource value: 0x7f0c0040
			public const int applause_severity_slider = 2131492928;
			
			// aapt resource value: 0x7f0c0036
			public const int applause_show_info = 2131492918;
			
			// aapt resource value: 0x7f0c0041
			public const int applause_test_cycle_name = 2131492929;
			
			// aapt resource value: 0x7f0c0042
			public const int applause_test_cycles_layouts_flipper = 2131492930;
			
			// aapt resource value: 0x7f0c0043
			public const int applause_test_cycles_manual_edit = 2131492931;
			
			// aapt resource value: 0x7f0c0044
			public const int applause_test_cycles_select_cycle_btn = 2131492932;
			
			// aapt resource value: 0x7f0c0045
			public const int applause_testcycles_users_list = 2131492933;
			
			// aapt resource value: 0x7f0c0047
			public const int applause_tutorial_bottom_bar = 2131492935;
			
			// aapt resource value: 0x7f0c0046
			public const int applause_tutorial_container = 2131492934;
			
			// aapt resource value: 0x7f0c0050
			public const int applause_tutorial_layout = 2131492944;
			
			// aapt resource value: 0x7f0c004a
			public const int applause_tutorial_next_button = 2131492938;
			
			// aapt resource value: 0x7f0c0049
			public const int applause_tutorial_page_indicator = 2131492937;
			
			// aapt resource value: 0x7f0c0048
			public const int applause_tutorial_skip_button = 2131492936;
			
			// aapt resource value: 0x7f0c004b
			public const int applause_tutorial_step1_progressbar = 2131492939;
			
			// aapt resource value: 0x7f0c004c
			public const int applause_tutorial_step1_web_view = 2131492940;
			
			// aapt resource value: 0x7f0c004d
			public const int applause_tutorial_step2_image = 2131492941;
			
			// aapt resource value: 0x7f0c004e
			public const int applause_tutorial_step2_label1 = 2131492942;
			
			// aapt resource value: 0x7f0c004f
			public const int applause_tutorial_step2_label2 = 2131492943;
			
			// aapt resource value: 0x7f0c0051
			public const int applause_user_avatar = 2131492945;
			
			// aapt resource value: 0x7f0c0052
			public const int applause_user_name = 2131492946;
			
			// aapt resource value: 0x7f0c003c
			public const int applause_video_play_button = 2131492924;
			
			// aapt resource value: 0x7f0c0054
			public const int applause_video_record_layout = 2131492948;
			
			// aapt resource value: 0x7f0c0053
			public const int applause_video_view = 2131492947;
			
			// aapt resource value: 0x7f0c0057
			public const int applause_welcome_screen_confirm_btn = 2131492951;
			
			// aapt resource value: 0x7f0c0055
			public const int applause_welcome_screen_container = 2131492949;
			
			// aapt resource value: 0x7f0c0056
			public const int applause_welcome_screen_content = 2131492950;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f090000
			public const int applause_default_circle_indicator_orientation = 2131296256;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int applause_beta_login_page = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int applause_dialog_footer = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int applause_dialog_generic = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int applause_dialog_type_chooser = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int applause_editor = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int applause_feedback = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int applause_feedback_copy = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int applause_feedback_header = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int applause_feedback_title = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int applause_header_beta = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int applause_header_normal = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int applause_header_quick = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int applause_login_error_box = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int applause_login_normal = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int applause_login_page_credentials = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int applause_login_quick = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int applause_problem = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int applause_problem_description = 2130903057;
			
			// aapt resource value: 0x7f030012
			public const int applause_problem_header = 2130903058;
			
			// aapt resource value: 0x7f030013
			public const int applause_problem_horizontal_list_tooltip = 2130903059;
			
			// aapt resource value: 0x7f030014
			public const int applause_problem_new = 2130903060;
			
			// aapt resource value: 0x7f030015
			public const int applause_problem_sub_header = 2130903061;
			
			// aapt resource value: 0x7f030016
			public const int applause_problem_wifi_only = 2130903062;
			
			// aapt resource value: 0x7f030017
			public const int applause_report = 2130903063;
			
			// aapt resource value: 0x7f030018
			public const int applause_screenshot_element = 2130903064;
			
			// aapt resource value: 0x7f030019
			public const int applause_screenshot_loader = 2130903065;
			
			// aapt resource value: 0x7f03001a
			public const int applause_severity_widget = 2130903066;
			
			// aapt resource value: 0x7f03001b
			public const int applause_testcycle = 2130903067;
			
			// aapt resource value: 0x7f03001c
			public const int applause_testcycles = 2130903068;
			
			// aapt resource value: 0x7f03001d
			public const int applause_testcycles_header = 2130903069;
			
			// aapt resource value: 0x7f03001e
			public const int applause_testcycles_input = 2130903070;
			
			// aapt resource value: 0x7f03001f
			public const int applause_testcycles_list = 2130903071;
			
			// aapt resource value: 0x7f030020
			public const int applause_tutorial = 2130903072;
			
			// aapt resource value: 0x7f030021
			public const int applause_tutorial_step_1 = 2130903073;
			
			// aapt resource value: 0x7f030022
			public const int applause_tutorial_step_2 = 2130903074;
			
			// aapt resource value: 0x7f030023
			public const int applause_tutorial_step_3 = 2130903075;
			
			// aapt resource value: 0x7f030024
			public const int applause_tutorial_step_4 = 2130903076;
			
			// aapt resource value: 0x7f030025
			public const int applause_tutorial_step_5 = 2130903077;
			
			// aapt resource value: 0x7f030026
			public const int applause_tutorial_step_6 = 2130903078;
			
			// aapt resource value: 0x7f030027
			public const int applause_user = 2130903079;
			
			// aapt resource value: 0x7f030028
			public const int applause_video_player = 2130903080;
			
			// aapt resource value: 0x7f030029
			public const int applause_video_record_layout = 2130903081;
			
			// aapt resource value: 0x7f03002a
			public const int applause_welcome_screen = 2130903082;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f050000
			public const int applasue_font_montserrat_bold = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int applause_font_awesome = 2131034113;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f0a0000
			public const int applause_accept_icon = 2131361792;
			
			// aapt resource value: 0x7f0a0001
			public const int applause_add_screenshot_icon = 2131361793;
			
			// aapt resource value: 0x7f0a0002
			public const int applause_adding_from_gallery_error = 2131361794;
			
			// aapt resource value: 0x7f0a0003
			public const int applause_bug_icon = 2131361795;
			
			// aapt resource value: 0x7f0a0004
			public const int applause_close_icon = 2131361796;
			
			// aapt resource value: 0x7f0a0005
			public const int applause_default_variant = 2131361797;
			
			// aapt resource value: 0x7f0a0006
			public const int applause_delete_screenshot_negative = 2131361798;
			
			// aapt resource value: 0x7f0a0007
			public const int applause_delete_screenshot_positive = 2131361799;
			
			// aapt resource value: 0x7f0a0008
			public const int applause_delete_screenshot_short = 2131361800;
			
			// aapt resource value: 0x7f0a0009
			public const int applause_delete_screenshot_title = 2131361801;
			
			// aapt resource value: 0x7f0a000a
			public const int applause_delete_video_title = 2131361802;
			
			// aapt resource value: 0x7f0a000b
			public const int applause_dialog_info = 2131361803;
			
			// aapt resource value: 0x7f0a000c
			public const int applause_dialog_or = 2131361804;
			
			// aapt resource value: 0x7f0a000d
			public const int applause_disabled_build_body = 2131361805;
			
			// aapt resource value: 0x7f0a000e
			public const int applause_disabled_build_kill_button = 2131361806;
			
			// aapt resource value: 0x7f0a000f
			public const int applause_disabled_build_title = 2131361807;
			
			// aapt resource value: 0x7f0a0010
			public const int applause_edit_screenshot = 2131361808;
			
			// aapt resource value: 0x7f0a0011
			public const int applause_edit_screenshot_short = 2131361809;
			
			// aapt resource value: 0x7f0a0012
			public const int applause_eraser_icon = 2131361810;
			
			// aapt resource value: 0x7f0a0013
			public const int applause_feedback_desc = 2131361811;
			
			// aapt resource value: 0x7f0a0014
			public const int applause_feedback_header_title = 2131361812;
			
			// aapt resource value: 0x7f0a0015
			public const int applause_feedback_hint = 2131361813;
			
			// aapt resource value: 0x7f0a0016
			public const int applause_feedback_icon = 2131361814;
			
			// aapt resource value: 0x7f0a0017
			public const int applause_feedback_no_rating_store = 2131361815;
			
			// aapt resource value: 0x7f0a0018
			public const int applause_feedback_title = 2131361816;
			
			// aapt resource value: 0x7f0a0019
			public const int applause_feedback_toast_no_message = 2131361817;
			
			// aapt resource value: 0x7f0a001a
			public const int applause_feedback_toast_no_rating = 2131361818;
			
			// aapt resource value: 0x7f0a001b
			public const int applause_give_feedback = 2131361819;
			
			// aapt resource value: 0x7f0a001c
			public const int applause_hide_icon = 2131361820;
			
			// aapt resource value: 0x7f0a001d
			public const int applause_include_screenshot = 2131361821;
			
			// aapt resource value: 0x7f0a001e
			public const int applause_library_name = 2131361822;
			
			// aapt resource value: 0x7f0a001f
			public const int applause_library_version = 2131361823;
			
			// aapt resource value: 0x7f0a0020
			public const int applause_login_anon_login_button = 2131361824;
			
			// aapt resource value: 0x7f0a0021
			public const int applause_login_app_version = 2131361825;
			
			// aapt resource value: 0x7f0a0022
			public const int applause_login_beta_get_passcode_button = 2131361826;
			
			// aapt resource value: 0x7f0a0023
			public const int applause_login_beta_get_passcode_failure = 2131361827;
			
			// aapt resource value: 0x7f0a0024
			public const int applause_login_beta_get_passcode_label = 2131361828;
			
			// aapt resource value: 0x7f0a0025
			public const int applause_login_beta_get_passcode_success = 2131361829;
			
			// aapt resource value: 0x7f0a0026
			public const int applause_login_beta_go_back = 2131361830;
			
			// aapt resource value: 0x7f0a0027
			public const int applause_login_beta_hint = 2131361831;
			
			// aapt resource value: 0x7f0a0028
			public const int applause_login_beta_subtitle = 2131361832;
			
			// aapt resource value: 0x7f0a0029
			public const int applause_login_beta_title = 2131361833;
			
			// aapt resource value: 0x7f0a002a
			public const int applause_login_choose_from_list = 2131361834;
			
			// aapt resource value: 0x7f0a002b
			public const int applause_login_error_API_EXCEPTION = 2131361835;
			
			// aapt resource value: 0x7f0a002c
			public const int applause_login_error_APPLICATION_INACTIVE = 2131361836;
			
			// aapt resource value: 0x7f0a002d
			public const int applause_login_error_BAD_APPLICATION = 2131361837;
			
			// aapt resource value: 0x7f0a002e
			public const int applause_login_error_BAD_CREDENTIALS = 2131361838;
			
			// aapt resource value: 0x7f0a002f
			public const int applause_login_error_BAD_ENVIRONMENT = 2131361839;
			
			// aapt resource value: 0x7f0a0030
			public const int applause_login_error_TOO_MANY_DEVICES = 2131361840;
			
			// aapt resource value: 0x7f0a0031
			public const int applause_login_error_box_title = 2131361841;
			
			// aapt resource value: 0x7f0a0032
			public const int applause_login_failed = 2131361842;
			
			// aapt resource value: 0x7f0a0033
			public const int applause_login_forgot_passcode = 2131361843;
			
			// aapt resource value: 0x7f0a0034
			public const int applause_login_identifyProgress = 2131361844;
			
			// aapt resource value: 0x7f0a0035
			public const int applause_login_login_button = 2131361845;
			
			// aapt resource value: 0x7f0a0036
			public const int applause_login_password_hint = 2131361846;
			
			// aapt resource value: 0x7f0a0037
			public const int applause_login_progress = 2131361847;
			
			// aapt resource value: 0x7f0a0038
			public const int applause_login_quick_subtitle = 2131361848;
			
			// aapt resource value: 0x7f0a0039
			public const int applause_login_subtitle = 2131361849;
			
			// aapt resource value: 0x7f0a003a
			public const int applause_login_title = 2131361850;
			
			// aapt resource value: 0x7f0a003b
			public const int applause_login_username_hint = 2131361851;
			
			// aapt resource value: 0x7f0a003c
			public const int applause_login_wrong_credentials = 2131361852;
			
			// aapt resource value: 0x7f0a003d
			public const int applause_missing_permission = 2131361853;
			
			// aapt resource value: 0x7f0a003e
			public const int applause_next_screenshot_icon = 2131361854;
			
			// aapt resource value: 0x7f0a003f
			public const int applause_notification_text_anonymous_user = 2131361855;
			
			// aapt resource value: 0x7f0a0040
			public const int applause_notification_text_auto_login = 2131361856;
			
			// aapt resource value: 0x7f0a0041
			public const int applause_notification_text_login = 2131361857;
			
			// aapt resource value: 0x7f0a0042
			public const int applause_notification_text_report = 2131361858;
			
			// aapt resource value: 0x7f0a0043
			public const int applause_notification_text_report_with_feedback = 2131361859;
			
			// aapt resource value: 0x7f0a0044
			public const int applause_notification_text_stop_video = 2131361860;
			
			// aapt resource value: 0x7f0a0045
			public const int applause_notification_update_text = 2131361861;
			
			// aapt resource value: 0x7f0a0046
			public const int applause_notification_update_ticker = 2131361862;
			
			// aapt resource value: 0x7f0a0047
			public const int applause_notification_update_title = 2131361863;
			
			// aapt resource value: 0x7f0a0048
			public const int applause_notification_upload = 2131361864;
			
			// aapt resource value: 0x7f0a0049
			public const int applause_notification_video_cancel_action = 2131361865;
			
			// aapt resource value: 0x7f0a004a
			public const int applause_notification_video_save_action = 2131361866;
			
			// aapt resource value: 0x7f0a004b
			public const int applause_pencil_icon = 2131361867;
			
			// aapt resource value: 0x7f0a004c
			public const int applause_problem_action_performed_hint = 2131361868;
			
			// aapt resource value: 0x7f0a004d
			public const int applause_problem_action_performed_label = 2131361869;
			
			// aapt resource value: 0x7f0a004e
			public const int applause_problem_actual_result_hint = 2131361870;
			
			// aapt resource value: 0x7f0a004f
			public const int applause_problem_actual_result_label = 2131361871;
			
			// aapt resource value: 0x7f0a0050
			public const int applause_problem_add_attachment = 2131361872;
			
			// aapt resource value: 0x7f0a0051
			public const int applause_problem_add_from_camera = 2131361873;
			
			// aapt resource value: 0x7f0a0052
			public const int applause_problem_add_from_gallery = 2131361874;
			
			// aapt resource value: 0x7f0a0053
			public const int applause_problem_add_screenshot = 2131361875;
			
			// aapt resource value: 0x7f0a0054
			public const int applause_problem_attachment_type_dialog_title = 2131361876;
			
			// aapt resource value: 0x7f0a0055
			public const int applause_problem_attachment_type_dialog_video_notice = 2131361877;
			
			// aapt resource value: 0x7f0a0056
			public const int applause_problem_attachments_label = 2131361878;
			
			// aapt resource value: 0x7f0a0057
			public const int applause_problem_backward_compatibility_template = 2131361879;
			
			// aapt resource value: 0x7f0a0058
			public const int applause_problem_bug_title_hint = 2131361880;
			
			// aapt resource value: 0x7f0a0059
			public const int applause_problem_bug_title_label = 2131361881;
			
			// aapt resource value: 0x7f0a005a
			public const int applause_problem_desc = 2131361882;
			
			// aapt resource value: 0x7f0a005b
			public const int applause_problem_header_test_cycle = 2131361883;
			
			// aapt resource value: 0x7f0a005c
			public const int applause_problem_header_title = 2131361884;
			
			// aapt resource value: 0x7f0a005d
			public const int applause_problem_hint = 2131361885;
			
			// aapt resource value: 0x7f0a005e
			public const int applause_problem_includes = 2131361886;
			
			// aapt resource value: 0x7f0a005f
			public const int applause_problem_play_video = 2131361887;
			
			// aapt resource value: 0x7f0a0060
			public const int applause_problem_severity_label = 2131361888;
			
			// aapt resource value: 0x7f0a0061
			public const int applause_problem_take_video = 2131361889;
			
			// aapt resource value: 0x7f0a0062
			public const int applause_problem_title = 2131361890;
			
			// aapt resource value: 0x7f0a0063
			public const int applause_problem_toast_no_message = 2131361891;
			
			// aapt resource value: 0x7f0a0064
			public const int applause_problem_wifi_only = 2131361892;
			
			// aapt resource value: 0x7f0a0065
			public const int applause_rate_this_application = 2131361893;
			
			// aapt resource value: 0x7f0a0066
			public const int applause_report_a_bug = 2131361894;
			
			// aapt resource value: 0x7f0a0067
			public const int applause_select_picture = 2131361895;
			
			// aapt resource value: 0x7f0a0068
			public const int applause_select_test_cycle_desc = 2131361896;
			
			// aapt resource value: 0x7f0a0069
			public const int applause_send_icon = 2131361897;
			
			// aapt resource value: 0x7f0a006a
			public const int applause_send_screenshot_desc = 2131361898;
			
			// aapt resource value: 0x7f0a006b
			public const int applause_severity_level_critical = 2131361899;
			
			// aapt resource value: 0x7f0a006c
			public const int applause_severity_level_high = 2131361900;
			
			// aapt resource value: 0x7f0a006d
			public const int applause_severity_level_low = 2131361901;
			
			// aapt resource value: 0x7f0a006e
			public const int applause_severity_level_medium = 2131361902;
			
			// aapt resource value: 0x7f0a006f
			public const int applause_shake_for_next_screenshot = 2131361903;
			
			// aapt resource value: 0x7f0a0070
			public const int applause_spray_icon = 2131361904;
			
			// aapt resource value: 0x7f0a0071
			public const int applause_test_cycle_hint = 2131361905;
			
			// aapt resource value: 0x7f0a0072
			public const int applause_test_cycles_manual = 2131361906;
			
			// aapt resource value: 0x7f0a0073
			public const int applause_test_cycles_select = 2131361907;
			
			// aapt resource value: 0x7f0a0074
			public const int applause_test_cycles_title = 2131361908;
			
			// aapt resource value: 0x7f0a0075
			public const int applause_toast_application_blocked = 2131361909;
			
			// aapt resource value: 0x7f0a0076
			public const int applause_toast_application_inactive = 2131361910;
			
			// aapt resource value: 0x7f0a0077
			public const int applause_toast_bad_application = 2131361911;
			
			// aapt resource value: 0x7f0a0078
			public const int applause_toast_bad_credentials = 2131361912;
			
			// aapt resource value: 0x7f0a0079
			public const int applause_toast_cant_identify = 2131361913;
			
			// aapt resource value: 0x7f0a007a
			public const int applause_toast_mandatory_update = 2131361914;
			
			// aapt resource value: 0x7f0a007b
			public const int applause_toast_recommended_update = 2131361915;
			
			// aapt resource value: 0x7f0a007c
			public const int applause_toast_too_many_devices = 2131361916;
			
			// aapt resource value: 0x7f0a007d
			public const int applause_toast_unknown_recommended_update = 2131361917;
			
			// aapt resource value: 0x7f0a007e
			public const int applause_trash_icon = 2131361918;
			
			// aapt resource value: 0x7f0a007f
			public const int applause_tutorial_done = 2131361919;
			
			// aapt resource value: 0x7f0a0080
			public const int applause_tutorial_next = 2131361920;
			
			// aapt resource value: 0x7f0a0081
			public const int applause_tutorial_skip = 2131361921;
			
			// aapt resource value: 0x7f0a0082
			public const int applause_tutorial_step2_label1 = 2131361922;
			
			// aapt resource value: 0x7f0a0083
			public const int applause_tutorial_step2_label2 = 2131361923;
			
			// aapt resource value: 0x7f0a0084
			public const int applause_tutorial_step3_label = 2131361924;
			
			// aapt resource value: 0x7f0a0085
			public const int applause_tutorial_step4_label = 2131361925;
			
			// aapt resource value: 0x7f0a0086
			public const int applause_tutorial_step5_label = 2131361926;
			
			// aapt resource value: 0x7f0a0087
			public const int applause_video_display_name = 2131361927;
			
			// aapt resource value: 0x7f0a0088
			public const int applause_video_recording_cancelled = 2131361928;
			
			// aapt resource value: 0x7f0a0089
			public const int applause_video_recording_ended = 2131361929;
			
			// aapt resource value: 0x7f0a008a
			public const int applause_video_recording_failed_to_start = 2131361930;
			
			// aapt resource value: 0x7f0a008b
			public const int applause_video_recording_has_started = 2131361931;
			
			// aapt resource value: 0x7f0a008c
			public const int applause_welcome_screen_confirm = 2131361932;
			
			// aapt resource value: 0x7f0a008d
			public const int applause_welcome_screen_header = 2131361933;
			
			// aapt resource value: 0x7f0a008e
			public const int applause_welcome_screen_temp_text = 2131361934;
			
			// aapt resource value: 0x7f0a008f
			public const int applause_wrong_manifest = 2131361935;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f0b0000
			public const int applause_alert_dialog = 2131427328;
			
			// aapt resource value: 0x7f0b0001
			public const int applause_blue_rating_bar = 2131427329;
			
			// aapt resource value: 0x7f0b0002
			public const int applause_button = 2131427330;
			
			// aapt resource value: 0x7f0b0003
			public const int applause_button_parent = 2131427331;
			
			// aapt resource value: 0x7f0b0011
			public const int applause_button_parent_parent = 2131427345;
			
			// aapt resource value: 0x7f0b0004
			public const int applause_dialog = 2131427332;
			
			// aapt resource value: 0x7f0b0005
			public const int applause_editor_button = 2131427333;
			
			// aapt resource value: 0x7f0b0006
			public const int applause_input = 2131427334;
			
			// aapt resource value: 0x7f0b0007
			public const int applause_or_text_divider = 2131427335;
			
			// aapt resource value: 0x7f0b0008
			public const int applause_report_attachments_bar = 2131427336;
			
			// aapt resource value: 0x7f0b0009
			public const int applause_report_input = 2131427337;
			
			// aapt resource value: 0x7f0b000a
			public const int applause_report_input_parnet = 2131427338;
			
			// aapt resource value: 0x7f0b000b
			public const int applause_report_inputs_bar = 2131427339;
			
			// aapt resource value: 0x7f0b000c
			public const int applause_report_label = 2131427340;
			
			// aapt resource value: 0x7f0b000d
			public const int applause_severity_slider_label = 2131427341;
			
			// aapt resource value: 0x7f0b000e
			public const int applause_tutorial_bottom_button = 2131427342;
			
			// aapt resource value: 0x7f0b000f
			public const int applause_tutorial_label = 2131427343;
			
			// aapt resource value: 0x7f0b0010
			public const int applause_tutorial_tooltip = 2131427344;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
