#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("DroidDemo.Resource", IsApplication=true)]

namespace DroidDemo
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f050000
			public const int applause_fab_bottom_down = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int applause_fab_bottom_up = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int applause_fab_scale_down = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int applause_fab_scale_up = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int applause_fab_slide_in_from_left = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int applause_fab_slide_in_from_right = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int applause_fab_slide_out_to_left = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int applause_fab_slide_out_to_right = 2131034119;
			
			// aapt resource value: 0x7f050008
			public const int applause_login_error_box_slide_in = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int applause_login_error_box_slide_out = 2131034121;
			
			// aapt resource value: 0x7f05000a
			public const int applause_pulse = 2131034122;
			
			// aapt resource value: 0x7f05000b
			public const int applause_shake = 2131034123;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Boolean
		{
			
			// aapt resource value: 0x7f080000
			public const int applause_default_circle_indicator_centered = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int applause_default_circle_indicator_snap = 2131230721;
			
			static Boolean()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Boolean()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f09007c
			public const int applause_add_attachment_action = 2131296380;
			
			// aapt resource value: 0x7f090000
			public const int applause_add_attachment_action_normal = 2131296256;
			
			// aapt resource value: 0x7f090001
			public const int applause_add_attachment_action_pressed = 2131296257;
			
			// aapt resource value: 0x7f090002
			public const int applause_add_attachment_background = 2131296258;
			
			// aapt resource value: 0x7f090003
			public const int applause_add_attachment_divider = 2131296259;
			
			// aapt resource value: 0x7f090004
			public const int applause_add_attachment_label = 2131296260;
			
			// aapt resource value: 0x7f090005
			public const int applause_add_attachment_title = 2131296261;
			
			// aapt resource value: 0x7f090006
			public const int applause_button_bg = 2131296262;
			
			// aapt resource value: 0x7f090007
			public const int applause_button_bg_disabled = 2131296263;
			
			// aapt resource value: 0x7f090008
			public const int applause_button_bg_pressed = 2131296264;
			
			// aapt resource value: 0x7f090009
			public const int applause_button_text = 2131296265;
			
			// aapt resource value: 0x7f09000a
			public const int applause_default_circle_indicator_fill_color = 2131296266;
			
			// aapt resource value: 0x7f09000b
			public const int applause_default_circle_indicator_page_color = 2131296267;
			
			// aapt resource value: 0x7f09000c
			public const int applause_default_circle_indicator_stroke_color = 2131296268;
			
			// aapt resource value: 0x7f09000d
			public const int applause_default_input_color = 2131296269;
			
			// aapt resource value: 0x7f09000e
			public const int applause_default_input_hint_color = 2131296270;
			
			// aapt resource value: 0x7f09007d
			public const int applause_dialog_action = 2131296381;
			
			// aapt resource value: 0x7f09000f
			public const int applause_dialog_action_normal = 2131296271;
			
			// aapt resource value: 0x7f090010
			public const int applause_dialog_action_pressed = 2131296272;
			
			// aapt resource value: 0x7f090011
			public const int applause_dialog_body_text = 2131296273;
			
			// aapt resource value: 0x7f09007e
			public const int applause_dialog_dismiss = 2131296382;
			
			// aapt resource value: 0x7f090012
			public const int applause_dialog_dismiss_normal = 2131296274;
			
			// aapt resource value: 0x7f090013
			public const int applause_dialog_dismiss_pressed = 2131296275;
			
			// aapt resource value: 0x7f090014
			public const int applause_editor_bg = 2131296276;
			
			// aapt resource value: 0x7f090015
			public const int applause_editor_menu_button_background_normal = 2131296277;
			
			// aapt resource value: 0x7f090016
			public const int applause_editor_menu_button_background_pressed = 2131296278;
			
			// aapt resource value: 0x7f090017
			public const int applause_editor_menu_button_selected_background_normal = 2131296279;
			
			// aapt resource value: 0x7f090018
			public const int applause_editor_menu_button_selected_background_pressed = 2131296280;
			
			// aapt resource value: 0x7f090019
			public const int applause_editor_menu_label_background_normal = 2131296281;
			
			// aapt resource value: 0x7f09001a
			public const int applause_editor_menu_label_background_pressed = 2131296282;
			
			// aapt resource value: 0x7f09001b
			public const int applause_editor_menu_label_text = 2131296283;
			
			// aapt resource value: 0x7f09001c
			public const int applause_falcon_blue = 2131296284;
			
			// aapt resource value: 0x7f09001d
			public const int applause_falcon_blue_tint_130 = 2131296285;
			
			// aapt resource value: 0x7f09001e
			public const int applause_falcon_blue_tint_150 = 2131296286;
			
			// aapt resource value: 0x7f09001f
			public const int applause_falcon_blue_tint_170 = 2131296287;
			
			// aapt resource value: 0x7f090020
			public const int applause_falcon_blue_tint_30 = 2131296288;
			
			// aapt resource value: 0x7f090021
			public const int applause_falcon_blue_tint_50 = 2131296289;
			
			// aapt resource value: 0x7f090022
			public const int applause_falcon_blue_tint_70 = 2131296290;
			
			// aapt resource value: 0x7f090023
			public const int applause_falcon_danger = 2131296291;
			
			// aapt resource value: 0x7f090024
			public const int applause_falcon_dark = 2131296292;
			
			// aapt resource value: 0x7f090025
			public const int applause_falcon_dark_tint_60 = 2131296293;
			
			// aapt resource value: 0x7f090026
			public const int applause_falcon_dark_tint_80 = 2131296294;
			
			// aapt resource value: 0x7f090027
			public const int applause_falcon_dark_tint_80_tran_25 = 2131296295;
			
			// aapt resource value: 0x7f090028
			public const int applause_falcon_dark_tint_90 = 2131296296;
			
			// aapt resource value: 0x7f090029
			public const int applause_falcon_dark_tran_75 = 2131296297;
			
			// aapt resource value: 0x7f09002a
			public const int applause_falcon_dark_tran_80 = 2131296298;
			
			// aapt resource value: 0x7f09002b
			public const int applause_falcon_dark_tran_85 = 2131296299;
			
			// aapt resource value: 0x7f09002c
			public const int applause_falcon_dark_tran_90 = 2131296300;
			
			// aapt resource value: 0x7f09002d
			public const int applause_falcon_light = 2131296301;
			
			// aapt resource value: 0x7f09002e
			public const int applause_falcon_light_tint_60 = 2131296302;
			
			// aapt resource value: 0x7f09002f
			public const int applause_falcon_light_tint_80 = 2131296303;
			
			// aapt resource value: 0x7f090030
			public const int applause_falcon_light_tint_90 = 2131296304;
			
			// aapt resource value: 0x7f090031
			public const int applause_falcon_light_tint_90_tran_25 = 2131296305;
			
			// aapt resource value: 0x7f090032
			public const int applause_falcon_light_tran_15 = 2131296306;
			
			// aapt resource value: 0x7f090033
			public const int applause_falcon_light_tran_25 = 2131296307;
			
			// aapt resource value: 0x7f090034
			public const int applause_falcon_light_tran_75 = 2131296308;
			
			// aapt resource value: 0x7f090035
			public const int applause_falcon_orange = 2131296309;
			
			// aapt resource value: 0x7f090036
			public const int applause_falcon_red = 2131296310;
			
			// aapt resource value: 0x7f090037
			public const int applause_falcon_red_dark = 2131296311;
			
			// aapt resource value: 0x7f090038
			public const int applause_falcon_warning = 2131296312;
			
			// aapt resource value: 0x7f090039
			public const int applause_falcon_yellow = 2131296313;
			
			// aapt resource value: 0x7f09003a
			public const int applause_input_cursor_color = 2131296314;
			
			// aapt resource value: 0x7f09003b
			public const int applause_loader_end_color = 2131296315;
			
			// aapt resource value: 0x7f09003c
			public const int applause_loader_start_color = 2131296316;
			
			// aapt resource value: 0x7f09003d
			public const int applause_login_body_background = 2131296317;
			
			// aapt resource value: 0x7f09003e
			public const int applause_login_button_background = 2131296318;
			
			// aapt resource value: 0x7f09003f
			public const int applause_login_button_background_pressed = 2131296319;
			
			// aapt resource value: 0x7f09007f
			public const int applause_login_color_selector = 2131296383;
			
			// aapt resource value: 0x7f090040
			public const int applause_login_divider_focused = 2131296320;
			
			// aapt resource value: 0x7f090041
			public const int applause_login_divider_unfocused = 2131296321;
			
			// aapt resource value: 0x7f090042
			public const int applause_login_error_box_background = 2131296322;
			
			// aapt resource value: 0x7f090043
			public const int applause_login_error_box_text = 2131296323;
			
			// aapt resource value: 0x7f090044
			public const int applause_login_footer_background = 2131296324;
			
			// aapt resource value: 0x7f090045
			public const int applause_login_footer_text = 2131296325;
			
			// aapt resource value: 0x7f090046
			public const int applause_login_header = 2131296326;
			
			// aapt resource value: 0x7f090047
			public const int applause_login_header_background = 2131296327;
			
			// aapt resource value: 0x7f090048
			public const int applause_login_input_label = 2131296328;
			
			// aapt resource value: 0x7f090049
			public const int applause_login_main_page_background = 2131296329;
			
			// aapt resource value: 0x7f09004a
			public const int applause_login_quick_list_pressed_item = 2131296330;
			
			// aapt resource value: 0x7f09004b
			public const int applause_login_row_text = 2131296331;
			
			// aapt resource value: 0x7f09004c
			public const int applause_login_subheader = 2131296332;
			
			// aapt resource value: 0x7f09004d
			public const int applause_production_feedback_background = 2131296333;
			
			// aapt resource value: 0x7f09004e
			public const int applause_report_action_bar_background = 2131296334;
			
			// aapt resource value: 0x7f09004f
			public const int applause_report_actionbar_background = 2131296335;
			
			// aapt resource value: 0x7f090050
			public const int applause_report_actionbar_text_color = 2131296336;
			
			// aapt resource value: 0x7f090051
			public const int applause_report_background = 2131296337;
			
			// aapt resource value: 0x7f090080
			public const int applause_report_bug = 2131296384;
			
			// aapt resource value: 0x7f090052
			public const int applause_report_bug_bg_normal = 2131296338;
			
			// aapt resource value: 0x7f090053
			public const int applause_report_bug_bg_pressed = 2131296339;
			
			// aapt resource value: 0x7f090054
			public const int applause_report_bug_bg_underline = 2131296340;
			
			// aapt resource value: 0x7f090055
			public const int applause_report_bug_text_normal = 2131296341;
			
			// aapt resource value: 0x7f090056
			public const int applause_report_bug_text_pressed = 2131296342;
			
			// aapt resource value: 0x7f090081
			public const int applause_report_feedback = 2131296385;
			
			// aapt resource value: 0x7f090057
			public const int applause_report_feedback_bg_normal = 2131296343;
			
			// aapt resource value: 0x7f090058
			public const int applause_report_feedback_bg_pressed = 2131296344;
			
			// aapt resource value: 0x7f090059
			public const int applause_report_feedback_bg_underline = 2131296345;
			
			// aapt resource value: 0x7f09005a
			public const int applause_report_feedback_text_normal = 2131296346;
			
			// aapt resource value: 0x7f09005b
			public const int applause_report_feedback_text_pressed = 2131296347;
			
			// aapt resource value: 0x7f09005c
			public const int applause_report_in_app_record_text_color = 2131296348;
			
			// aapt resource value: 0x7f09005d
			public const int applause_report_problem_add_step_color = 2131296349;
			
			// aapt resource value: 0x7f09005e
			public const int applause_report_problem_attachment_background = 2131296350;
			
			// aapt resource value: 0x7f09005f
			public const int applause_report_problem_background = 2131296351;
			
			// aapt resource value: 0x7f090060
			public const int applause_report_problem_edit_bar_focused = 2131296352;
			
			// aapt resource value: 0x7f090061
			public const int applause_report_problem_edit_bar_normal = 2131296353;
			
			// aapt resource value: 0x7f090062
			public const int applause_report_problem_label_color = 2131296354;
			
			// aapt resource value: 0x7f090063
			public const int applause_report_problem_label_color_focused = 2131296355;
			
			// aapt resource value: 0x7f090064
			public const int applause_report_problem_value_color = 2131296356;
			
			// aapt resource value: 0x7f090065
			public const int applause_report_problem_value_hint_color = 2131296357;
			
			// aapt resource value: 0x7f090066
			public const int applause_report_settings_background = 2131296358;
			
			// aapt resource value: 0x7f090067
			public const int applause_report_settings_background_pressed = 2131296359;
			
			// aapt resource value: 0x7f090068
			public const int applause_report_settings_divider = 2131296360;
			
			// aapt resource value: 0x7f090069
			public const int applause_report_settings_label = 2131296361;
			
			// aapt resource value: 0x7f09006a
			public const int applause_report_settings_sublabel = 2131296362;
			
			// aapt resource value: 0x7f09006b
			public const int applause_report_severity_critical = 2131296363;
			
			// aapt resource value: 0x7f09006c
			public const int applause_report_severity_high = 2131296364;
			
			// aapt resource value: 0x7f09006d
			public const int applause_report_severity_low = 2131296365;
			
			// aapt resource value: 0x7f09006e
			public const int applause_report_severity_medium = 2131296366;
			
			// aapt resource value: 0x7f09006f
			public const int applause_report_severity_progress = 2131296367;
			
			// aapt resource value: 0x7f090070
			public const int applause_screenshot_thumbnail_border_pressed = 2131296368;
			
			// aapt resource value: 0x7f090071
			public const int applause_screenshot_thumbnail_pressed = 2131296369;
			
			// aapt resource value: 0x7f090072
			public const int applause_transparent = 2131296370;
			
			// aapt resource value: 0x7f090073
			public const int applause_tutorial_bar_divider_background = 2131296371;
			
			// aapt resource value: 0x7f090074
			public const int applause_tutorial_button_pressed = 2131296372;
			
			// aapt resource value: 0x7f090075
			public const int applause_tutorial_buttons_text = 2131296373;
			
			// aapt resource value: 0x7f090076
			public const int applause_tutorial_first_step_background = 2131296374;
			
			// aapt resource value: 0x7f090077
			public const int applause_tutorial_header_text = 2131296375;
			
			// aapt resource value: 0x7f090078
			public const int applause_tutorial_indicator_fill_color = 2131296376;
			
			// aapt resource value: 0x7f090079
			public const int applause_tutorial_indicator_stroke_color = 2131296377;
			
			// aapt resource value: 0x7f09007a
			public const int applause_tutorial_next_steps_background = 2131296378;
			
			// aapt resource value: 0x7f09007b
			public const int applause_tutorial_welcome_screen_background = 2131296379;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f070004
			public const int applause_action_bar_height = 2131165188;
			
			// aapt resource value: 0x7f070005
			public const int applause_action_bar_more_width = 2131165189;
			
			// aapt resource value: 0x7f070006
			public const int applause_add_attachment_background_corner_radius = 2131165190;
			
			// aapt resource value: 0x7f070007
			public const int applause_add_attachment_padding = 2131165191;
			
			// aapt resource value: 0x7f070008
			public const int applause_button_corner_radius = 2131165192;
			
			// aapt resource value: 0x7f070009
			public const int applause_default_circle_indicator_radius = 2131165193;
			
			// aapt resource value: 0x7f07000a
			public const int applause_default_circle_indicator_stroke_width = 2131165194;
			
			// aapt resource value: 0x7f070002
			public const int applause_dialog_horizontal_margin = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int applause_dialog_vertical_margin = 2131165187;
			
			// aapt resource value: 0x7f07000b
			public const int applause_editor_label_background_radius = 2131165195;
			
			// aapt resource value: 0x7f07000c
			public const int applause_fab_menu_item_distance = 2131165196;
			
			// aapt resource value: 0x7f07000d
			public const int applause_fab_size_mini = 2131165197;
			
			// aapt resource value: 0x7f07000e
			public const int applause_fab_size_normal = 2131165198;
			
			// aapt resource value: 0x7f07000f
			public const int applause_feedback_description_text_size = 2131165199;
			
			// aapt resource value: 0x7f070010
			public const int applause_feedback_large_padding = 2131165200;
			
			// aapt resource value: 0x7f070011
			public const int applause_feedback_small_padding = 2131165201;
			
			// aapt resource value: 0x7f070012
			public const int applause_feedback_star_padding = 2131165202;
			
			// aapt resource value: 0x7f070013
			public const int applause_labels_text_size = 2131165203;
			
			// aapt resource value: 0x7f070014
			public const int applause_login_footer_height = 2131165204;
			
			// aapt resource value: 0x7f070000
			public const int applause_login_header_top_padding = 2131165184;
			
			// aapt resource value: 0x7f070015
			public const int applause_login_side_padding = 2131165205;
			
			// aapt resource value: 0x7f070016
			public const int applause_login_standard_padding = 2131165206;
			
			// aapt resource value: 0x7f070017
			public const int applause_login_top_padding = 2131165207;
			
			// aapt resource value: 0x7f070018
			public const int applause_production_feedback_standard_padding = 2131165208;
			
			// aapt resource value: 0x7f070019
			public const int applause_report_buttons_height = 2131165209;
			
			// aapt resource value: 0x7f07001a
			public const int applause_report_buttons_margin_inner = 2131165210;
			
			// aapt resource value: 0x7f07001b
			public const int applause_report_buttons_margin_outer = 2131165211;
			
			// aapt resource value: 0x7f07001c
			public const int applause_report_buttons_width = 2131165212;
			
			// aapt resource value: 0x7f07001d
			public const int applause_report_capture_video_stroke_size = 2131165213;
			
			// aapt resource value: 0x7f07001e
			public const int applause_report_capture_video_stroke_size_negative = 2131165214;
			
			// aapt resource value: 0x7f07001f
			public const int applause_report_default_padding = 2131165215;
			
			// aapt resource value: 0x7f070020
			public const int applause_report_edit_underline_dash_gap = 2131165216;
			
			// aapt resource value: 0x7f070021
			public const int applause_report_edit_underline_dash_width = 2131165217;
			
			// aapt resource value: 0x7f070022
			public const int applause_report_edit_underline_size = 2131165218;
			
			// aapt resource value: 0x7f070023
			public const int applause_report_edit_underline_start = 2131165219;
			
			// aapt resource value: 0x7f070024
			public const int applause_report_seekbar_height = 2131165220;
			
			// aapt resource value: 0x7f070025
			public const int applause_report_seekbar_thumb_radius = 2131165221;
			
			// aapt resource value: 0x7f070026
			public const int applause_report_settings_avatar_size = 2131165222;
			
			// aapt resource value: 0x7f070027
			public const int applause_screenshot_height = 2131165223;
			
			// aapt resource value: 0x7f070001
			public const int applause_tutorial_bottom_bar_height = 2131165185;
			
			// aapt resource value: 0x7f070028
			public const int applause_tutorial_template_image_bottom_padding = 2131165224;
			
			// aapt resource value: 0x7f070029
			public const int applause_tutorial_template_image_top_padding = 2131165225;
			
			// aapt resource value: 0x7f07002a
			public const int applause_tutorial_template_side_padding = 2131165226;
			
			// aapt resource value: 0x7f07002b
			public const int applause_tutorial_template_subheader_bottom_padding = 2131165227;
			
			// aapt resource value: 0x7f07002c
			public const int applause_tutorial_template_top_padding = 2131165228;
			
			// aapt resource value: 0x7f07002d
			public const int applause_tutorial_webview_side_margin = 2131165229;
			
			// aapt resource value: 0x7f07002e
			public const int applause_tutorial_webview_top_margin = 2131165230;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int applause_add_attachment = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int applause_add_attachment_action_background = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int applause_add_attachment_background = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int applause_add_attachment_normal = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int applause_add_attachment_pressed = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int applause_avatar = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int applause_button = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int applause_checbox_off_normal = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int applause_checbox_off_pressed = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int applause_checbox_on_normal = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int applause_checbox_on_pressed = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int applause_checkbox = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int applause_color_cursor = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int applause_editor_blur_icon = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int applause_editor_blur_white_icon = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int applause_editor_brush_icon = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int applause_editor_brush_white_icon = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int applause_editor_discard = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int applause_editor_done = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int applause_editor_fab_menu_background = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int applause_editor_reset_icon = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int applause_exlamation_mark = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int applause_fab_add = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int applause_large_exlamation_mark = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int applause_loader = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int applause_login_input_background = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int applause_login_input_focused = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int applause_login_input_unfocused = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int applause_login_quick_list_selector = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int applause_problem_actions_edittext_background = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int applause_problem_actions_edittext_focused = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int applause_problem_actions_edittext_unfocused = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int applause_problem_edittext_background = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int applause_problem_edittext_focused = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int applause_problem_edittext_unfocused = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int applause_report_actionbar_attach = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int applause_report_actionbar_more = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int applause_report_actionbar_send = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int applause_report_bug = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int applause_report_bug_normal = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int applause_report_bug_pressed = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int applause_report_cog = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int applause_report_feedback = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int applause_report_feedback_normal = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int applause_report_feedback_pressed = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int applause_report_seekbar_critical = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int applause_report_seekbar_high = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int applause_report_seekbar_low = 2130837551;
			
			// aapt resource value: 0x7f020030
			public const int applause_report_seekbar_medium = 2130837552;
			
			// aapt resource value: 0x7f020031
			public const int applause_report_seekbar_thumb_critical = 2130837553;
			
			// aapt resource value: 0x7f020032
			public const int applause_report_seekbar_thumb_high = 2130837554;
			
			// aapt resource value: 0x7f020033
			public const int applause_report_seekbar_thumb_low = 2130837555;
			
			// aapt resource value: 0x7f020034
			public const int applause_report_seekbar_thumb_medium = 2130837556;
			
			// aapt resource value: 0x7f020035
			public const int applause_report_settings_item_background = 2130837557;
			
			// aapt resource value: 0x7f020036
			public const int applause_report_video_capture = 2130837558;
			
			// aapt resource value: 0x7f020037
			public const int applause_report_video_capture_background = 2130837559;
			
			// aapt resource value: 0x7f020038
			public const int applause_report_video_capture_normal = 2130837560;
			
			// aapt resource value: 0x7f020039
			public const int applause_report_video_capture_pressed = 2130837561;
			
			// aapt resource value: 0x7f02003a
			public const int applause_screenshot_thumbnail_overlay = 2130837562;
			
			// aapt resource value: 0x7f02003b
			public const int applause_settings_back = 2130837563;
			
			// aapt resource value: 0x7f02003c
			public const int applause_shadow = 2130837564;
			
			// aapt resource value: 0x7f02003d
			public const int applause_shadow_chunk = 2130837565;
			
			// aapt resource value: 0x7f02003e
			public const int applause_star = 2130837566;
			
			// aapt resource value: 0x7f02003f
			public const int applause_star_active = 2130837567;
			
			// aapt resource value: 0x7f020040
			public const int applause_star_normal = 2130837568;
			
			// aapt resource value: 0x7f020041
			public const int applause_star_pressed = 2130837569;
			
			// aapt resource value: 0x7f020042
			public const int applause_tutorial_button_background = 2130837570;
			
			// aapt resource value: 0x7f020043
			public const int applause_tutorial_step1 = 2130837571;
			
			// aapt resource value: 0x7f020044
			public const int applause_tutorial_step2 = 2130837572;
			
			// aapt resource value: 0x7f020045
			public const int applause_tutorial_step2_utest = 2130837573;
			
			// aapt resource value: 0x7f020046
			public const int applause_tutorial_step3 = 2130837574;
			
			// aapt resource value: 0x7f020047
			public const int applause_tutorial_step4 = 2130837575;
			
			// aapt resource value: 0x7f020048
			public const int applause_video_cancel_action = 2130837576;
			
			// aapt resource value: 0x7f020049
			public const int applause_video_play = 2130837577;
			
			// aapt resource value: 0x7f02004a
			public const int applause_video_play_button = 2130837578;
			
			// aapt resource value: 0x7f02004b
			public const int applause_video_save_action = 2130837579;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f0d0074
			public const int applause_attach_file = 2131558516;
			
			// aapt resource value: 0x7f0d0073
			public const int applause_discard_report = 2131558515;
			
			// aapt resource value: 0x7f0d0009
			public const int applause_editor_actions_menu = 2131558409;
			
			// aapt resource value: 0x7f0d000b
			public const int applause_editor_blur_action = 2131558411;
			
			// aapt resource value: 0x7f0d000c
			public const int applause_editor_brush_action = 2131558412;
			
			// aapt resource value: 0x7f0d0070
			public const int applause_editor_discard_action = 2131558512;
			
			// aapt resource value: 0x7f0d000a
			public const int applause_editor_reset_action = 2131558410;
			
			// aapt resource value: 0x7f0d0071
			public const int applause_editor_save_action = 2131558513;
			
			// aapt resource value: 0x7f0d000e
			public const int applause_feedback_attach_screenshot_fragment = 2131558414;
			
			// aapt resource value: 0x7f0d000f
			public const int applause_feedback_description_fragment = 2131558415;
			
			// aapt resource value: 0x7f0d0011
			public const int applause_feedback_include_screenshot_check_box = 2131558417;
			
			// aapt resource value: 0x7f0d0010
			public const int applause_feedback_preview_fragment = 2131558416;
			
			// aapt resource value: 0x7f0d000d
			public const int applause_feedback_rating_fragment = 2131558413;
			
			// aapt resource value: 0x7f0d0001
			public const int applause_generic_dialog_body = 2131558401;
			
			// aapt resource value: 0x7f0d0002
			public const int applause_generic_dialog_negative_btn = 2131558402;
			
			// aapt resource value: 0x7f0d0003
			public const int applause_generic_dialog_positive_btn = 2131558403;
			
			// aapt resource value: 0x7f0d0000
			public const int applause_generic_dialog_title = 2131558400;
			
			// aapt resource value: 0x7f0d0021
			public const int applause_login_btn_anon_login = 2131558433;
			
			// aapt resource value: 0x7f0d0022
			public const int applause_login_btn_login = 2131558434;
			
			// aapt resource value: 0x7f0d0019
			public const int applause_login_container = 2131558425;
			
			// aapt resource value: 0x7f0d001a
			public const int applause_login_dialog_password_auth_view = 2131558426;
			
			// aapt resource value: 0x7f0d001e
			public const int applause_login_email_edit = 2131558430;
			
			// aapt resource value: 0x7f0d001d
			public const int applause_login_email_label = 2131558429;
			
			// aapt resource value: 0x7f0d0016
			public const int applause_login_error_close = 2131558422;
			
			// aapt resource value: 0x7f0d0014
			public const int applause_login_error_container = 2131558420;
			
			// aapt resource value: 0x7f0d0015
			public const int applause_login_error_text = 2131558421;
			
			// aapt resource value: 0x7f0d0017
			public const int applause_login_footer_container = 2131558423;
			
			// aapt resource value: 0x7f0d0018
			public const int applause_login_footer_version = 2131558424;
			
			// aapt resource value: 0x7f0d001c
			public const int applause_login_header2 = 2131558428;
			
			// aapt resource value: 0x7f0d001b
			public const int applause_login_header_container = 2131558427;
			
			// aapt resource value: 0x7f0d0013
			public const int applause_login_loading_container = 2131558419;
			
			// aapt resource value: 0x7f0d0020
			public const int applause_login_password_edit = 2131558432;
			
			// aapt resource value: 0x7f0d001f
			public const int applause_login_password_label = 2131558431;
			
			// aapt resource value: 0x7f0d0023
			public const int applause_login_users_list = 2131558435;
			
			// aapt resource value: 0x7f0d0008
			public const int applause_overlay = 2131558408;
			
			// aapt resource value: 0x7f0d0028
			public const int applause_problem_action_performed_add_after = 2131558440;
			
			// aapt resource value: 0x7f0d0026
			public const int applause_problem_action_performed_edittext = 2131558438;
			
			// aapt resource value: 0x7f0d002f
			public const int applause_problem_action_performed_fragment = 2131558447;
			
			// aapt resource value: 0x7f0d0024
			public const int applause_problem_action_performed_label = 2131558436;
			
			// aapt resource value: 0x7f0d0027
			public const int applause_problem_action_performed_position = 2131558439;
			
			// aapt resource value: 0x7f0d002a
			public const int applause_problem_actual_result_edittext = 2131558442;
			
			// aapt resource value: 0x7f0d0031
			public const int applause_problem_actual_result_fragment = 2131558449;
			
			// aapt resource value: 0x7f0d0029
			public const int applause_problem_actual_result_label = 2131558441;
			
			// aapt resource value: 0x7f0d002d
			public const int applause_problem_expected_result_edittext = 2131558445;
			
			// aapt resource value: 0x7f0d0030
			public const int applause_problem_expected_result_fragment = 2131558448;
			
			// aapt resource value: 0x7f0d002c
			public const int applause_problem_expected_result_label = 2131558444;
			
			// aapt resource value: 0x7f0d0033
			public const int applause_problem_preview_fragment = 2131558451;
			
			// aapt resource value: 0x7f0d0032
			public const int applause_problem_severity_fragment = 2131558450;
			
			// aapt resource value: 0x7f0d0035
			public const int applause_problem_severity_seekbar = 2131558453;
			
			// aapt resource value: 0x7f0d0034
			public const int applause_problem_severity_textview = 2131558452;
			
			// aapt resource value: 0x7f0d0037
			public const int applause_problem_title_edittext = 2131558455;
			
			// aapt resource value: 0x7f0d002e
			public const int applause_problem_title_fragment = 2131558446;
			
			// aapt resource value: 0x7f0d0036
			public const int applause_problem_title_label = 2131558454;
			
			// aapt resource value: 0x7f0d0039
			public const int applause_production_feedback_dialog_hint = 2131558457;
			
			// aapt resource value: 0x7f0d003a
			public const int applause_production_feedback_dialog_negative_button = 2131558458;
			
			// aapt resource value: 0x7f0d003b
			public const int applause_production_feedback_dialog_positive_button = 2131558459;
			
			// aapt resource value: 0x7f0d0038
			public const int applause_production_feedback_dialog_title = 2131558456;
			
			// aapt resource value: 0x7f0d003d
			public const int applause_rating_1 = 2131558461;
			
			// aapt resource value: 0x7f0d003e
			public const int applause_rating_2 = 2131558462;
			
			// aapt resource value: 0x7f0d003f
			public const int applause_rating_3 = 2131558463;
			
			// aapt resource value: 0x7f0d0040
			public const int applause_rating_4 = 2131558464;
			
			// aapt resource value: 0x7f0d0041
			public const int applause_rating_5 = 2131558465;
			
			// aapt resource value: 0x7f0d003c
			public const int applause_rating_bar = 2131558460;
			
			// aapt resource value: 0x7f0d0045
			public const int applause_report_action_settings = 2131558469;
			
			// aapt resource value: 0x7f0d0046
			public const int applause_report_action_update_available = 2131558470;
			
			// aapt resource value: 0x7f0d002b
			public const int applause_report_add_attachment = 2131558443;
			
			// aapt resource value: 0x7f0d0006
			public const int applause_report_add_from_camera = 2131558406;
			
			// aapt resource value: 0x7f0d0005
			public const int applause_report_add_from_gallery = 2131558405;
			
			// aapt resource value: 0x7f0d0004
			public const int applause_report_add_screenshot = 2131558404;
			
			// aapt resource value: 0x7f0d0042
			public const int applause_report_animator = 2131558466;
			
			// aapt resource value: 0x7f0d0049
			public const int applause_report_attachments_list = 2131558473;
			
			// aapt resource value: 0x7f0d0047
			public const int applause_report_dialog_bug = 2131558471;
			
			// aapt resource value: 0x7f0d0048
			public const int applause_report_dialog_feedback = 2131558472;
			
			// aapt resource value: 0x7f0d0043
			public const int applause_report_main_container = 2131558467;
			
			// aapt resource value: 0x7f0d0012
			public const int applause_report_message_edit = 2131558418;
			
			// aapt resource value: 0x7f0d0052
			public const int applause_report_settings_available_version = 2131558482;
			
			// aapt resource value: 0x7f0d004c
			public const int applause_report_settings_back = 2131558476;
			
			// aapt resource value: 0x7f0d0057
			public const int applause_report_settings_checkbox = 2131558487;
			
			// aapt resource value: 0x7f0d004b
			public const int applause_report_settings_container = 2131558475;
			
			// aapt resource value: 0x7f0d0050
			public const int applause_report_settings_current_version = 2131558480;
			
			// aapt resource value: 0x7f0d004e
			public const int applause_report_settings_login_label = 2131558478;
			
			// aapt resource value: 0x7f0d004f
			public const int applause_report_settings_login_user = 2131558479;
			
			// aapt resource value: 0x7f0d0055
			public const int applause_report_settings_show_tutorial = 2131558485;
			
			// aapt resource value: 0x7f0d0054
			public const int applause_report_settings_switch_accounts = 2131558484;
			
			// aapt resource value: 0x7f0d0051
			public const int applause_report_settings_update = 2131558481;
			
			// aapt resource value: 0x7f0d0053
			public const int applause_report_settings_update_bar = 2131558483;
			
			// aapt resource value: 0x7f0d0056
			public const int applause_report_settings_wifi = 2131558486;
			
			// aapt resource value: 0x7f0d0007
			public const int applause_report_take_video = 2131558407;
			
			// aapt resource value: 0x7f0d004a
			public const int applause_report_test_cycle_name = 2131558474;
			
			// aapt resource value: 0x7f0d0058
			public const int applause_screenshot_container = 2131558488;
			
			// aapt resource value: 0x7f0d005c
			public const int applause_screenshot_loader = 2131558492;
			
			// aapt resource value: 0x7f0d005a
			public const int applause_screenshot_overlay = 2131558490;
			
			// aapt resource value: 0x7f0d0059
			public const int applause_screenshot_small = 2131558489;
			
			// aapt resource value: 0x7f0d0072
			public const int applause_send_report = 2131558514;
			
			// aapt resource value: 0x7f0d0025
			public const int applause_steps_container = 2131558437;
			
			// aapt resource value: 0x7f0d005d
			public const int applause_test_cycle_name = 2131558493;
			
			// aapt resource value: 0x7f0d005e
			public const int applause_test_cycles_layouts_flipper = 2131558494;
			
			// aapt resource value: 0x7f0d005f
			public const int applause_test_cycles_manual_edit = 2131558495;
			
			// aapt resource value: 0x7f0d0060
			public const int applause_test_cycles_select_cycle_btn = 2131558496;
			
			// aapt resource value: 0x7f0d0061
			public const int applause_testcycles_users_list = 2131558497;
			
			// aapt resource value: 0x7f0d0044
			public const int applause_toolbar_container = 2131558468;
			
			// aapt resource value: 0x7f0d0063
			public const int applause_tutorial_container = 2131558499;
			
			// aapt resource value: 0x7f0d0062
			public const int applause_tutorial_layout = 2131558498;
			
			// aapt resource value: 0x7f0d0066
			public const int applause_tutorial_next_button = 2131558502;
			
			// aapt resource value: 0x7f0d0065
			public const int applause_tutorial_page_indicator = 2131558501;
			
			// aapt resource value: 0x7f0d0064
			public const int applause_tutorial_skip_button = 2131558500;
			
			// aapt resource value: 0x7f0d0067
			public const int applause_tutorial_step1_progressbar = 2131558503;
			
			// aapt resource value: 0x7f0d0068
			public const int applause_tutorial_step1_web_view = 2131558504;
			
			// aapt resource value: 0x7f0d006b
			public const int applause_tutorial_step_image = 2131558507;
			
			// aapt resource value: 0x7f0d006a
			public const int applause_tutorial_step_image_container = 2131558506;
			
			// aapt resource value: 0x7f0d006c
			public const int applause_tutorial_step_subtitle = 2131558508;
			
			// aapt resource value: 0x7f0d0069
			public const int applause_tutorial_step_title = 2131558505;
			
			// aapt resource value: 0x7f0d004d
			public const int applause_user_avatar = 2131558477;
			
			// aapt resource value: 0x7f0d006d
			public const int applause_user_name = 2131558509;
			
			// aapt resource value: 0x7f0d005b
			public const int applause_video_play_button = 2131558491;
			
			// aapt resource value: 0x7f0d006e
			public const int applause_video_view = 2131558510;
			
			// aapt resource value: 0x7f0d006f
			public const int myButton = 2131558511;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f0a0000
			public const int applause_default_circle_indicator_orientation = 2131361792;
			
			// aapt resource value: 0x7f0a0001
			public const int applause_default_rating = 2131361793;
			
			// aapt resource value: 0x7f0a0002
			public const int applause_fab_menu_animation_item_speed = 2131361794;
			
			// aapt resource value: 0x7f0a0003
			public const int applause_login_copyright_visibility = 2131361795;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int applause_dialog_generic = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int applause_dialog_type_chooser = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int applause_editor = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int applause_feedback = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int applause_feedback_attach_screenshot_fragment = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int applause_feedback_description_fragment = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int applause_feedback_rating_fragment = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int applause_login_container = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int applause_login_error_box = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int applause_login_footer = 2130968585;
			
			// aapt resource value: 0x7f04000a
			public const int applause_login_main_page = 2130968586;
			
			// aapt resource value: 0x7f04000b
			public const int applause_login_normal = 2130968587;
			
			// aapt resource value: 0x7f04000c
			public const int applause_login_quick = 2130968588;
			
			// aapt resource value: 0x7f04000d
			public const int applause_problem_action_performed_fragment = 2130968589;
			
			// aapt resource value: 0x7f04000e
			public const int applause_problem_action_performed_step = 2130968590;
			
			// aapt resource value: 0x7f04000f
			public const int applause_problem_actual_result_fragment = 2130968591;
			
			// aapt resource value: 0x7f040010
			public const int applause_problem_add_screenshot = 2130968592;
			
			// aapt resource value: 0x7f040011
			public const int applause_problem_expected_result_fragment = 2130968593;
			
			// aapt resource value: 0x7f040012
			public const int applause_problem_new = 2130968594;
			
			// aapt resource value: 0x7f040013
			public const int applause_problem_severity_fragment = 2130968595;
			
			// aapt resource value: 0x7f040014
			public const int applause_problem_title_fragment = 2130968596;
			
			// aapt resource value: 0x7f040015
			public const int applause_production_feedback = 2130968597;
			
			// aapt resource value: 0x7f040016
			public const int applause_rating_bar = 2130968598;
			
			// aapt resource value: 0x7f040017
			public const int applause_report_container = 2130968599;
			
			// aapt resource value: 0x7f040018
			public const int applause_report_main = 2130968600;
			
			// aapt resource value: 0x7f040019
			public const int applause_report_preview_fragment = 2130968601;
			
			// aapt resource value: 0x7f04001a
			public const int applause_report_settings = 2130968602;
			
			// aapt resource value: 0x7f04001b
			public const int applause_screenshot_element = 2130968603;
			
			// aapt resource value: 0x7f04001c
			public const int applause_screenshot_loader = 2130968604;
			
			// aapt resource value: 0x7f04001d
			public const int applause_shadow = 2130968605;
			
			// aapt resource value: 0x7f04001e
			public const int applause_testcycle = 2130968606;
			
			// aapt resource value: 0x7f04001f
			public const int applause_testcycles = 2130968607;
			
			// aapt resource value: 0x7f040020
			public const int applause_testcycles_header = 2130968608;
			
			// aapt resource value: 0x7f040021
			public const int applause_testcycles_input = 2130968609;
			
			// aapt resource value: 0x7f040022
			public const int applause_testcycles_list = 2130968610;
			
			// aapt resource value: 0x7f040023
			public const int applause_tutorial = 2130968611;
			
			// aapt resource value: 0x7f040024
			public const int applause_tutorial_step_1 = 2130968612;
			
			// aapt resource value: 0x7f040025
			public const int applause_tutorial_step_template = 2130968613;
			
			// aapt resource value: 0x7f040026
			public const int applause_user = 2130968614;
			
			// aapt resource value: 0x7f040027
			public const int applause_video_player = 2130968615;
			
			// aapt resource value: 0x7f040028
			public const int Main = 2130968616;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f0c0000
			public const int applause_editor_menu = 2131492864;
			
			// aapt resource value: 0x7f0c0001
			public const int applause_feedback_menu = 2131492865;
			
			// aapt resource value: 0x7f0c0002
			public const int applause_problem_menu = 2131492866;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int Icon = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f0600bc
			public const int app_name = 2131099836;
			
			// aapt resource value: 0x7f060000
			public const int applause_action_discard = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int applause_action_send = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int applause_add_in_app_screenshot_toast_message = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int applause_adding_from_gallery_error = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int applause_attachment_action_sheet_negative = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int applause_attachment_library_not_available_message = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int applause_auto_login_toast_hint = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int applause_autologin_toast_message = 2131099655;
			
			// aapt resource value: 0x7f0600b4
			public const int applause_beta_brand_name = 2131099828;
			
			// aapt resource value: 0x7f060008
			public const int applause_bug_type_functional = 2131099656;
			
			// aapt resource value: 0x7f060009
			public const int applause_bug_type_load = 2131099657;
			
			// aapt resource value: 0x7f06000a
			public const int applause_bug_type_localization = 2131099658;
			
			// aapt resource value: 0x7f06000b
			public const int applause_bug_type_security = 2131099659;
			
			// aapt resource value: 0x7f06000c
			public const int applause_bug_type_usability = 2131099660;
			
			// aapt resource value: 0x7f06000d
			public const int applause_delete_attachment_title = 2131099661;
			
			// aapt resource value: 0x7f06000e
			public const int applause_delete_screenshot_negative = 2131099662;
			
			// aapt resource value: 0x7f06000f
			public const int applause_delete_screenshot_positive = 2131099663;
			
			// aapt resource value: 0x7f060010
			public const int applause_disabled_build_body = 2131099664;
			
			// aapt resource value: 0x7f060011
			public const int applause_disabled_build_kill_button = 2131099665;
			
			// aapt resource value: 0x7f060012
			public const int applause_disabled_build_title = 2131099666;
			
			// aapt resource value: 0x7f060013
			public const int applause_edit_screenshot = 2131099667;
			
			// aapt resource value: 0x7f060014
			public const int applause_edit_video = 2131099668;
			
			// aapt resource value: 0x7f060015
			public const int applause_editor_blur_label = 2131099669;
			
			// aapt resource value: 0x7f060016
			public const int applause_editor_brush_label = 2131099670;
			
			// aapt resource value: 0x7f060017
			public const int applause_editor_discard = 2131099671;
			
			// aapt resource value: 0x7f060018
			public const int applause_editor_reset_label = 2131099672;
			
			// aapt resource value: 0x7f060019
			public const int applause_editor_save = 2131099673;
			
			// aapt resource value: 0x7f06001a
			public const int applause_feedback_add_remove_screenshot_label = 2131099674;
			
			// aapt resource value: 0x7f06001b
			public const int applause_feedback_header_title = 2131099675;
			
			// aapt resource value: 0x7f06001c
			public const int applause_feedback_hint = 2131099676;
			
			// aapt resource value: 0x7f06001d
			public const int applause_feedback_include_screenshot_switch_accessibility_label = 2131099677;
			
			// aapt resource value: 0x7f06001e
			public const int applause_feedback_included_screenshot_accessibility_label = 2131099678;
			
			// aapt resource value: 0x7f06001f
			public const int applause_feedback_included_screenshot_hint_accessibility_label = 2131099679;
			
			// aapt resource value: 0x7f060020
			public const int applause_feedback_message_accessibility_label = 2131099680;
			
			// aapt resource value: 0x7f060021
			public const int applause_feedback_rating_control_accessibility_label = 2131099681;
			
			// aapt resource value: 0x7f060022
			public const int applause_feedback_screenshot_description = 2131099682;
			
			// aapt resource value: 0x7f060023
			public const int applause_feedback_screenshot_preview_title = 2131099683;
			
			// aapt resource value: 0x7f060024
			public const int applause_feedback_toast_no_message = 2131099684;
			
			// aapt resource value: 0x7f0600b5
			public const int applause_font_family_medium = 2131099829;
			
			// aapt resource value: 0x7f060025
			public const int applause_give_feedback = 2131099685;
			
			// aapt resource value: 0x7f0600b6
			public const int applause_library_name = 2131099830;
			
			// aapt resource value: 0x7f0600b7
			public const int applause_library_version = 2131099831;
			
			// aapt resource value: 0x7f060026
			public const int applause_login_alt_title = 2131099686;
			
			// aapt resource value: 0x7f060027
			public const int applause_login_anon_login_button = 2131099687;
			
			// aapt resource value: 0x7f060028
			public const int applause_login_app_version = 2131099688;
			
			// aapt resource value: 0x7f060029
			public const int applause_login_buttons_seprator_label = 2131099689;
			
			// aapt resource value: 0x7f0600b8
			public const int applause_login_copyright = 2131099832;
			
			// aapt resource value: 0x7f06002a
			public const int applause_login_email_field_accessibility_label = 2131099690;
			
			// aapt resource value: 0x7f06002b
			public const int applause_login_email_field_hint_accessibility_label = 2131099691;
			
			// aapt resource value: 0x7f06002c
			public const int applause_login_error_API_EXCEPTION = 2131099692;
			
			// aapt resource value: 0x7f06002d
			public const int applause_login_error_APPLICATION_INACTIVE = 2131099693;
			
			// aapt resource value: 0x7f06002e
			public const int applause_login_error_BAD_ADDRESS = 2131099694;
			
			// aapt resource value: 0x7f06002f
			public const int applause_login_error_BAD_APPLICATION = 2131099695;
			
			// aapt resource value: 0x7f060030
			public const int applause_login_error_BAD_CREDENTIALS = 2131099696;
			
			// aapt resource value: 0x7f060031
			public const int applause_login_error_BAD_ENVIRONMENT = 2131099697;
			
			// aapt resource value: 0x7f060032
			public const int applause_login_error_BAD_SESSION = 2131099698;
			
			// aapt resource value: 0x7f060033
			public const int applause_login_error_TOO_MANY_DEVICES = 2131099699;
			
			// aapt resource value: 0x7f060034
			public const int applause_login_error_box_title = 2131099700;
			
			// aapt resource value: 0x7f060035
			public const int applause_login_failed_retry_toast_accessibility_label = 2131099701;
			
			// aapt resource value: 0x7f060036
			public const int applause_login_login_button = 2131099702;
			
			// aapt resource value: 0x7f060037
			public const int applause_login_password_field_accessibility_label = 2131099703;
			
			// aapt resource value: 0x7f060038
			public const int applause_login_password_field_hint_accessibility_label = 2131099704;
			
			// aapt resource value: 0x7f060039
			public const int applause_login_password_hint = 2131099705;
			
			// aapt resource value: 0x7f06003a
			public const int applause_login_prefixed_title = 2131099706;
			
			// aapt resource value: 0x7f06003b
			public const int applause_login_progress_message = 2131099707;
			
			// aapt resource value: 0x7f06003c
			public const int applause_login_quick_subtitle = 2131099708;
			
			// aapt resource value: 0x7f06003d
			public const int applause_login_sdk_version = 2131099709;
			
			// aapt resource value: 0x7f06003e
			public const int applause_login_subtitle = 2131099710;
			
			// aapt resource value: 0x7f06003f
			public const int applause_login_title = 2131099711;
			
			// aapt resource value: 0x7f060040
			public const int applause_login_username_hint = 2131099712;
			
			// aapt resource value: 0x7f060041
			public const int applause_login_welcome = 2131099713;
			
			// aapt resource value: 0x7f060042
			public const int applause_network_connection_established_toast_message = 2131099714;
			
			// aapt resource value: 0x7f060043
			public const int applause_network_lost_notification_message = 2131099715;
			
			// aapt resource value: 0x7f060044
			public const int applause_no_active_test_cycle_toast_message = 2131099716;
			
			// aapt resource value: 0x7f060045
			public const int applause_notification_text_report = 2131099717;
			
			// aapt resource value: 0x7f060046
			public const int applause_notification_text_report_with_feedback = 2131099718;
			
			// aapt resource value: 0x7f060047
			public const int applause_notification_text_stop_video = 2131099719;
			
			// aapt resource value: 0x7f060048
			public const int applause_notification_upload = 2131099720;
			
			// aapt resource value: 0x7f060049
			public const int applause_notification_video_cancel_action = 2131099721;
			
			// aapt resource value: 0x7f06004a
			public const int applause_notification_video_save_action = 2131099722;
			
			// aapt resource value: 0x7f06004b
			public const int applause_offline_test_cycle_negative = 2131099723;
			
			// aapt resource value: 0x7f06004c
			public const int applause_offline_test_cycle_title = 2131099724;
			
			// aapt resource value: 0x7f06004d
			public const int applause_problem_action_performed_alt_label = 2131099725;
			
			// aapt resource value: 0x7f06004e
			public const int applause_problem_action_performed_hint_more = 2131099726;
			
			// aapt resource value: 0x7f06004f
			public const int applause_problem_action_performed_label = 2131099727;
			
			// aapt resource value: 0x7f060050
			public const int applause_problem_actual_result_alt_label = 2131099728;
			
			// aapt resource value: 0x7f060051
			public const int applause_problem_actual_result_hint = 2131099729;
			
			// aapt resource value: 0x7f060052
			public const int applause_problem_actual_result_label = 2131099730;
			
			// aapt resource value: 0x7f060053
			public const int applause_problem_add_from_camera = 2131099731;
			
			// aapt resource value: 0x7f060054
			public const int applause_problem_add_from_gallery = 2131099732;
			
			// aapt resource value: 0x7f060055
			public const int applause_problem_add_screenshot = 2131099733;
			
			// aapt resource value: 0x7f060056
			public const int applause_problem_add_video_from_library = 2131099734;
			
			// aapt resource value: 0x7f060057
			public const int applause_problem_attachment_type_dialog_title = 2131099735;
			
			// aapt resource value: 0x7f060058
			public const int applause_problem_bug_severity_not_selected = 2131099736;
			
			// aapt resource value: 0x7f060059
			public const int applause_problem_bug_title_hint = 2131099737;
			
			// aapt resource value: 0x7f06005a
			public const int applause_problem_bug_title_label = 2131099738;
			
			// aapt resource value: 0x7f06005b
			public const int applause_problem_bug_title_placeholder = 2131099739;
			
			// aapt resource value: 0x7f06005c
			public const int applause_problem_bug_type_not_selected = 2131099740;
			
			// aapt resource value: 0x7f06005d
			public const int applause_problem_bug_type_title = 2131099741;
			
			// aapt resource value: 0x7f06005e
			public const int applause_problem_expected_result_alt_label = 2131099742;
			
			// aapt resource value: 0x7f06005f
			public const int applause_problem_expected_result_hint = 2131099743;
			
			// aapt resource value: 0x7f060060
			public const int applause_problem_expected_result_label = 2131099744;
			
			// aapt resource value: 0x7f060061
			public const int applause_problem_header_title = 2131099745;
			
			// aapt resource value: 0x7f060062
			public const int applause_problem_negative_bar_button = 2131099746;
			
			// aapt resource value: 0x7f060063
			public const int applause_problem_none_test_cycle = 2131099747;
			
			// aapt resource value: 0x7f060064
			public const int applause_problem_optional_result_hint = 2131099748;
			
			// aapt resource value: 0x7f060065
			public const int applause_problem_settings_label = 2131099749;
			
			// aapt resource value: 0x7f060066
			public const int applause_problem_severity_label = 2131099750;
			
			// aapt resource value: 0x7f060067
			public const int applause_problem_take_video = 2131099751;
			
			// aapt resource value: 0x7f060068
			public const int applause_problem_toast_no_message = 2131099752;
			
			// aapt resource value: 0x7f060069
			public const int applause_production_feedback_dialog_hint = 2131099753;
			
			// aapt resource value: 0x7f06006a
			public const int applause_production_feedback_dialog_negative_button = 2131099754;
			
			// aapt resource value: 0x7f06006b
			public const int applause_production_feedback_dialog_positive_button = 2131099755;
			
			// aapt resource value: 0x7f06006c
			public const int applause_production_feedback_dialog_subtitle = 2131099756;
			
			// aapt resource value: 0x7f06006d
			public const int applause_production_feedback_dialog_title = 2131099757;
			
			// aapt resource value: 0x7f06006e
			public const int applause_production_feedback_message_accessibility_label = 2131099758;
			
			// aapt resource value: 0x7f06006f
			public const int applause_production_feedback_too_long_message = 2131099759;
			
			// aapt resource value: 0x7f060070
			public const int applause_production_feedback_too_short_message = 2131099760;
			
			// aapt resource value: 0x7f060071
			public const int applause_quick_login_anonymous_user_section = 2131099761;
			
			// aapt resource value: 0x7f060072
			public const int applause_quick_login_cell_action_accessibility_label = 2131099762;
			
			// aapt resource value: 0x7f060073
			public const int applause_report_a_bug = 2131099763;
			
			// aapt resource value: 0x7f060074
			public const int applause_report_attachments_label = 2131099764;
			
			// aapt resource value: 0x7f060075
			public const int applause_report_attachments_notice = 2131099765;
			
			// aapt resource value: 0x7f060076
			public const int applause_report_attachments_test_cycle_label = 2131099766;
			
			// aapt resource value: 0x7f060077
			public const int applause_report_title = 2131099767;
			
			// aapt resource value: 0x7f060078
			public const int applause_screenshot_editor_accessibility_label = 2131099768;
			
			// aapt resource value: 0x7f060079
			public const int applause_screenshot_editor_cancel_accessibility_label = 2131099769;
			
			// aapt resource value: 0x7f06007a
			public const int applause_screenshot_editor_delete_accessibility_label = 2131099770;
			
			// aapt resource value: 0x7f06007b
			public const int applause_screenshot_editor_double_tap_info = 2131099771;
			
			// aapt resource value: 0x7f06007c
			public const int applause_screenshot_editor_drawing_area_accessibility_label = 2131099772;
			
			// aapt resource value: 0x7f06007d
			public const int applause_screenshot_editor_pencil_accessibility_label = 2131099773;
			
			// aapt resource value: 0x7f06007e
			public const int applause_screenshot_editor_save_accessibility_label = 2131099774;
			
			// aapt resource value: 0x7f06007f
			public const int applause_screenshot_editor_spray_accessibility_label = 2131099775;
			
			// aapt resource value: 0x7f060080
			public const int applause_screenshot_not_available_label = 2131099776;
			
			// aapt resource value: 0x7f0600b9
			public const int applause_sdk_brand_name = 2131099833;
			
			// aapt resource value: 0x7f060081
			public const int applause_select_test_cycle_desc = 2131099777;
			
			// aapt resource value: 0x7f060082
			public const int applause_settings_accounts_label = 2131099778;
			
			// aapt resource value: 0x7f060083
			public const int applause_settings_anonymous_user_label = 2131099779;
			
			// aapt resource value: 0x7f060084
			public const int applause_settings_close_accessibility_label = 2131099780;
			
			// aapt resource value: 0x7f060085
			public const int applause_settings_close_button = 2131099781;
			
			// aapt resource value: 0x7f060086
			public const int applause_settings_current_version = 2131099782;
			
			// aapt resource value: 0x7f060087
			public const int applause_settings_login_label = 2131099783;
			
			// aapt resource value: 0x7f060088
			public const int applause_settings_not_logged_in_label = 2131099784;
			
			// aapt resource value: 0x7f060089
			public const int applause_settings_title = 2131099785;
			
			// aapt resource value: 0x7f06008a
			public const int applause_settings_tutorial_label = 2131099786;
			
			// aapt resource value: 0x7f06008b
			public const int applause_settings_update_application = 2131099787;
			
			// aapt resource value: 0x7f06008c
			public const int applause_settings_wifi_label = 2131099788;
			
			// aapt resource value: 0x7f06008d
			public const int applause_severity_critical = 2131099789;
			
			// aapt resource value: 0x7f06008e
			public const int applause_severity_high = 2131099790;
			
			// aapt resource value: 0x7f06008f
			public const int applause_severity_low = 2131099791;
			
			// aapt resource value: 0x7f060090
			public const int applause_severity_medium = 2131099792;
			
			// aapt resource value: 0x7f060091
			public const int applause_shake_for_next_screenshot = 2131099793;
			
			// aapt resource value: 0x7f060092
			public const int applause_test_cycle_hint = 2131099794;
			
			// aapt resource value: 0x7f060093
			public const int applause_test_cycles_empty_not_allowed = 2131099795;
			
			// aapt resource value: 0x7f060094
			public const int applause_test_cycles_manual = 2131099796;
			
			// aapt resource value: 0x7f060095
			public const int applause_test_cycles_set = 2131099797;
			
			// aapt resource value: 0x7f060096
			public const int applause_test_cycles_title = 2131099798;
			
			// aapt resource value: 0x7f060097
			public const int applause_toast_application_blocked = 2131099799;
			
			// aapt resource value: 0x7f060098
			public const int applause_toast_cant_identify = 2131099800;
			
			// aapt resource value: 0x7f060099
			public const int applause_toast_recommended_update = 2131099801;
			
			// aapt resource value: 0x7f06009a
			public const int applause_tutorial_done = 2131099802;
			
			// aapt resource value: 0x7f06009b
			public const int applause_tutorial_get_started_button = 2131099803;
			
			// aapt resource value: 0x7f06009c
			public const int applause_tutorial_message_loading_error = 2131099804;
			
			// aapt resource value: 0x7f06009d
			public const int applause_tutorial_next = 2131099805;
			
			// aapt resource value: 0x7f06009e
			public const int applause_tutorial_skip = 2131099806;
			
			// aapt resource value: 0x7f06009f
			public const int applause_tutorial_step1_subtitle = 2131099807;
			
			// aapt resource value: 0x7f0600a0
			public const int applause_tutorial_step1_title = 2131099808;
			
			// aapt resource value: 0x7f0600a1
			public const int applause_tutorial_step1_title_utest = 2131099809;
			
			// aapt resource value: 0x7f0600a2
			public const int applause_tutorial_step2_subtitle = 2131099810;
			
			// aapt resource value: 0x7f0600a3
			public const int applause_tutorial_step2_subtitle_utest = 2131099811;
			
			// aapt resource value: 0x7f0600a4
			public const int applause_tutorial_step2_title = 2131099812;
			
			// aapt resource value: 0x7f0600a5
			public const int applause_tutorial_step3_subtitle = 2131099813;
			
			// aapt resource value: 0x7f0600a6
			public const int applause_tutorial_step3_subtitle_utest = 2131099814;
			
			// aapt resource value: 0x7f0600a7
			public const int applause_tutorial_step3_title = 2131099815;
			
			// aapt resource value: 0x7f0600a8
			public const int applause_tutorial_step4_subtitle = 2131099816;
			
			// aapt resource value: 0x7f0600a9
			public const int applause_tutorial_step4_title = 2131099817;
			
			// aapt resource value: 0x7f0600aa
			public const int applause_update_alert_install_button_label = 2131099818;
			
			// aapt resource value: 0x7f0600ab
			public const int applause_update_alert_negative_button_label = 2131099819;
			
			// aapt resource value: 0x7f0600ac
			public const int applause_update_application_alert_message = 2131099820;
			
			// aapt resource value: 0x7f0600ad
			public const int applause_update_application_alert_title = 2131099821;
			
			// aapt resource value: 0x7f0600ba
			public const int applause_video_display_name = 2131099834;
			
			// aapt resource value: 0x7f0600ae
			public const int applause_video_recording_cancelled = 2131099822;
			
			// aapt resource value: 0x7f0600af
			public const int applause_video_recording_ended = 2131099823;
			
			// aapt resource value: 0x7f0600b0
			public const int applause_video_recording_failed_to_start = 2131099824;
			
			// aapt resource value: 0x7f0600b1
			public const int applause_video_recording_has_started = 2131099825;
			
			// aapt resource value: 0x7f0600b2
			public const int applause_voice_over_drawing_info = 2131099826;
			
			// aapt resource value: 0x7f0600b3
			public const int applause_wrong_manifest = 2131099827;
			
			// aapt resource value: 0x7f0600bb
			public const int hello = 2131099835;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f0b0000
			public const int applause_action_bar = 2131427328;
			
			// aapt resource value: 0x7f0b0001
			public const int applause_action_bar_items = 2131427329;
			
			// aapt resource value: 0x7f0b0002
			public const int applause_action_bar_more = 2131427330;
			
			// aapt resource value: 0x7f0b0003
			public const int applause_action_bar_title = 2131427331;
			
			// aapt resource value: 0x7f0b0004
			public const int applause_add_attachment_action = 2131427332;
			
			// aapt resource value: 0x7f0b0005
			public const int applause_add_attachment_cancel = 2131427333;
			
			// aapt resource value: 0x7f0b0006
			public const int applause_add_attachment_label = 2131427334;
			
			// aapt resource value: 0x7f0b0007
			public const int applause_button = 2131427335;
			
			// aapt resource value: 0x7f0b0008
			public const int applause_dialog = 2131427336;
			
			// aapt resource value: 0x7f0b0009
			public const int applause_dialog_action = 2131427337;
			
			// aapt resource value: 0x7f0b000a
			public const int applause_dialog_body = 2131427338;
			
			// aapt resource value: 0x7f0b000b
			public const int applause_dialog_container = 2131427339;
			
			// aapt resource value: 0x7f0b000c
			public const int applause_dialog_dismiss = 2131427340;
			
			// aapt resource value: 0x7f0b000d
			public const int applause_dialog_title = 2131427341;
			
			// aapt resource value: 0x7f0b000e
			public const int applause_editor_actionbar = 2131427342;
			
			// aapt resource value: 0x7f0b000f
			public const int applause_editor_fab_menu_label = 2131427343;
			
			// aapt resource value: 0x7f0b0010
			public const int applause_editor_theme = 2131427344;
			
			// aapt resource value: 0x7f0b0011
			public const int applause_feedback_actionbar = 2131427345;
			
			// aapt resource value: 0x7f0b0012
			public const int applause_feedback_attach_container = 2131427346;
			
			// aapt resource value: 0x7f0b0013
			public const int applause_feedback_container = 2131427347;
			
			// aapt resource value: 0x7f0b0014
			public const int applause_feedback_label_dark = 2131427348;
			
			// aapt resource value: 0x7f0b0015
			public const int applause_feedback_rating_label = 2131427349;
			
			// aapt resource value: 0x7f0b0016
			public const int applause_feedback_screenshots_container = 2131427350;
			
			// aapt resource value: 0x7f0b0017
			public const int applause_feedback_separator = 2131427351;
			
			// aapt resource value: 0x7f0b0018
			public const int applause_feedback_theme = 2131427352;
			
			// aapt resource value: 0x7f0b0019
			public const int applause_input = 2131427353;
			
			// aapt resource value: 0x7f0b001a
			public const int applause_label = 2131427354;
			
			// aapt resource value: 0x7f0b001b
			public const int applause_login_anonymous_button = 2131427355;
			
			// aapt resource value: 0x7f0b001c
			public const int applause_login_button = 2131427356;
			
			// aapt resource value: 0x7f0b001d
			public const int applause_login_error_box = 2131427357;
			
			// aapt resource value: 0x7f0b001e
			public const int applause_login_error_box_close = 2131427358;
			
			// aapt resource value: 0x7f0b001f
			public const int applause_login_error_box_label = 2131427359;
			
			// aapt resource value: 0x7f0b0020
			public const int applause_login_error_box_title = 2131427360;
			
			// aapt resource value: 0x7f0b0021
			public const int applause_login_footer_ = 2131427361;
			
			// aapt resource value: 0x7f0b0022
			public const int applause_login_header = 2131427362;
			
			// aapt resource value: 0x7f0b0023
			public const int applause_login_input = 2131427363;
			
			// aapt resource value: 0x7f0b0024
			public const int applause_login_input_label = 2131427364;
			
			// aapt resource value: 0x7f0b0025
			public const int applause_login_quick_auth_row = 2131427365;
			
			// aapt resource value: 0x7f0b0026
			public const int applause_login_subheader1 = 2131427366;
			
			// aapt resource value: 0x7f0b0027
			public const int applause_login_subheader2 = 2131427367;
			
			// aapt resource value: 0x7f0b0028
			public const int applause_problem_action_performed_add_after = 2131427368;
			
			// aapt resource value: 0x7f0b0029
			public const int applause_problem_action_performed_label = 2131427369;
			
			// aapt resource value: 0x7f0b002a
			public const int applause_problem_action_performed_position = 2131427370;
			
			// aapt resource value: 0x7f0b002b
			public const int applause_problem_action_performed_value = 2131427371;
			
			// aapt resource value: 0x7f0b002c
			public const int applause_problem_actionbar = 2131427372;
			
			// aapt resource value: 0x7f0b002d
			public const int applause_problem_actual_result_label = 2131427373;
			
			// aapt resource value: 0x7f0b002e
			public const int applause_problem_actual_result_value = 2131427374;
			
			// aapt resource value: 0x7f0b002f
			public const int applause_problem_container = 2131427375;
			
			// aapt resource value: 0x7f0b0030
			public const int applause_problem_expected_result_label = 2131427376;
			
			// aapt resource value: 0x7f0b0031
			public const int applause_problem_expected_result_value = 2131427377;
			
			// aapt resource value: 0x7f0b0032
			public const int applause_problem_label = 2131427378;
			
			// aapt resource value: 0x7f0b0033
			public const int applause_problem_scrollview = 2131427379;
			
			// aapt resource value: 0x7f0b0034
			public const int applause_problem_severity_label = 2131427380;
			
			// aapt resource value: 0x7f0b0035
			public const int applause_problem_severity_value = 2131427381;
			
			// aapt resource value: 0x7f0b0036
			public const int applause_problem_theme = 2131427382;
			
			// aapt resource value: 0x7f0b0037
			public const int applause_problem_title_label = 2131427383;
			
			// aapt resource value: 0x7f0b0038
			public const int applause_problem_title_value = 2131427384;
			
			// aapt resource value: 0x7f0b0039
			public const int applause_problem_value = 2131427385;
			
			// aapt resource value: 0x7f0b003a
			public const int applause_production_feedback_input = 2131427386;
			
			// aapt resource value: 0x7f0b003b
			public const int applause_production_feedback_negative_action = 2131427387;
			
			// aapt resource value: 0x7f0b003c
			public const int applause_production_feedback_positive_action = 2131427388;
			
			// aapt resource value: 0x7f0b003d
			public const int applause_production_feedback_subtitle = 2131427389;
			
			// aapt resource value: 0x7f0b003e
			public const int applause_production_feedback_title = 2131427390;
			
			// aapt resource value: 0x7f0b003f
			public const int applause_rating_bar = 2131427391;
			
			// aapt resource value: 0x7f0b0040
			public const int applause_rating_bar_star = 2131427392;
			
			// aapt resource value: 0x7f0b0041
			public const int applause_report_action_bar = 2131427393;
			
			// aapt resource value: 0x7f0b0042
			public const int applause_report_action_bug_button = 2131427394;
			
			// aapt resource value: 0x7f0b0043
			public const int applause_report_action_buttons = 2131427395;
			
			// aapt resource value: 0x7f0b0044
			public const int applause_report_action_feedback_button = 2131427396;
			
			// aapt resource value: 0x7f0b0045
			public const int applause_report_attachments_label = 2131427397;
			
			// aapt resource value: 0x7f0b0046
			public const int applause_report_settings_divider = 2131427398;
			
			// aapt resource value: 0x7f0b0047
			public const int applause_report_settings_label = 2131427399;
			
			// aapt resource value: 0x7f0b0048
			public const int applause_report_settings_section = 2131427400;
			
			// aapt resource value: 0x7f0b0049
			public const int applause_report_settings_sublabel = 2131427401;
			
			// aapt resource value: 0x7f0b004a
			public const int applause_theme = 2131427402;
			
			// aapt resource value: 0x7f0b004b
			public const int applause_tutorial_bottom_button = 2131427403;
			
			// aapt resource value: 0x7f0b004c
			public const int applause_tutorial_divider = 2131427404;
			
			// aapt resource value: 0x7f0b004d
			public const int applause_tutorial_header = 2131427405;
			
			// aapt resource value: 0x7f0b004e
			public const int applause_tutorial_subheader = 2131427406;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
